/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package id.co.meda.apit.visual.form;

import id.co.meda.apit.enggine.dbkb.DBKBFirstCalculation;
import id.co.meda.apit.enggine.dbkb.model.Dhkmf;
import id.co.meda.apit.visual.controller.ControlDhkmf;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author PT. Databumi Indonesia
 */
public class FrmDhkmf extends javax.swing.JDialog {
    
    private ArrayList<Dhkmf> arrDhkmf;
    private String kodeDhkmf;  
    
    /**
     * Creates new form dialogDhkmf
     */
    public FrmDhkmf(java.awt.Frame parent, boolean modal, String kodeDhkmf) {
        super(parent, modal);
        initComponents();
        this.btnSimpan.setEnabled(false);
        this.btnLaporan.setEnabled(false);
        this.kodeDhkmf = kodeDhkmf;
        ControlDhkmf controller = new ControlDhkmf();
        cmbPilihTahun = controller.getComboBoxItem(cmbPilihTahun);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        cmbPilihTahun = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDhkmf = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Daftar Komponen Material");
        setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);
        setName("dialogDhkmf"); // NOI18N

        cmbPilihTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPilihTahunActionPerformed(evt);
            }
        });

        tableDhkmf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableDhkmf);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnLaporan.setText("Cetak Laporan");
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSimpan))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbPilihTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLaporan)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbPilihTahun)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLaporan)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSimpan)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        cmbPilihTahun.getAccessibleContext().setAccessibleName("comboTahun");

        setSize(new java.awt.Dimension(632, 566));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
       
        ControlDhkmf controller = new ControlDhkmf();
        controller.setArrDhkmf(arrDhkmf);
        ArrayList <Dhkmf> newArrDhkmf = controller.ambilDataTabel(tableDhkmf, arrDhkmf);
        controller.simpanKeDatabase(newArrDhkmf);    
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void cmbPilihTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPilihTahunActionPerformed
        // TODO add your handling code here:
         ControlDhkmf controller = new ControlDhkmf(this.kodeDhkmf,cmbPilihTahun.getSelectedItem()+"");
         arrDhkmf = controller.getArrDhkmf();
         tableDhkmf.setModel(controller.getTableModel());
         
         if(cmbPilihTahun.getSelectedIndex() != 0)
         {    
            this.btnSimpan.setEnabled(true);
            this.btnLaporan.setEnabled(true);
         }
    }//GEN-LAST:event_cmbPilihTahunActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // TODO add your handling code here:
        ControlDhkmf controller = new ControlDhkmf(this.kodeDhkmf,cmbPilihTahun.getSelectedItem()+"");
        controller.cetakLaporan(this.cmbPilihTahun.getSelectedItem()+"");
    }//GEN-LAST:event_btnLaporanActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox cmbPilihTahun;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableDhkmf;
    // End of variables declaration//GEN-END:variables

    
    
        
    
    }




