/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package id.co.meda.apit.visual.form;

import id.co.meda.apit.enggine.headreport.ModelHeadReport;
import id.co.meda.apit.enggine.jabatan.ModelJabatan;
import id.co.meda.apit.visual.controller.ControlEditReport;
import java.util.ArrayList;

/**
 *
 * @author PT. Databumi Indonesia
 */
public class FrmEditReport extends javax.swing.JDialog {

    private final ControlEditReport control = new ControlEditReport();
    
    /**
     * Creates new form FrmEditJabatan
     */
    public FrmEditReport(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inisiasiField();
    }
    
    private void inisiasiField()
    {
        //populate head
        ModelHeadReport head = control.getModelHead();
        
        this.NamaPemDaerahField.setText(head.getNamaPemDaerah());
        this.dinasDaerahField.setText(head.getDinasDaerah());
        this.alamatDinasField.setText(head.getAlamatDinas());
        
        //populate jabatan
       ArrayList<ModelJabatan> arrTemp = control.getArrModelJabatan();
       for(int i = 0; i < arrTemp.size();i++)
       {
           if(i==0)
           {       
                this.lblDP.setText(arrTemp.get(i).getJabatan());
                this.fieldNipDP.setText(arrTemp.get(i).getNip());
                this.fieldNamaDP.setText(arrTemp.get(i).getNama());
           }else if(i==1)
           {
                this.lblBP.setText(arrTemp.get(i).getJabatan());
                this.fieldNipBP.setText(arrTemp.get(i).getNip());
                this.fieldNamaBP.setText(arrTemp.get(i).getNama());
           }else if(i==2)
           {
                this.lblSP.setText(arrTemp.get(i).getJabatan());
                this.fieldNipSP.setText(arrTemp.get(i).getNip());
                this.fieldNamaSP.setText(arrTemp.get(i).getNama());
           }
       }
    }
    
    private void Simpan()
    {
       ArrayList<ModelJabatan> arrTemp = new ArrayList<ModelJabatan>();
       
       ModelJabatan model1 = new ModelJabatan();
       model1.setNip(this.fieldNipDP.getText());
       model1.setJabatan(this.lblDP.getText());
       model1.setNama(this.fieldNamaDP.getText());
       arrTemp.add(model1);
       
       ModelJabatan model2 = new ModelJabatan();
       model2.setNip(this.fieldNipBP.getText());
       model2.setJabatan(this.lblBP.getText());
       model2.setNama(this.fieldNamaBP.getText());
       arrTemp.add(model2);
       
       ModelJabatan model3 = new ModelJabatan();
       model3.setNip(this.fieldNipSP.getText());
       model3.setJabatan(this.lblSP.getText());
       model3.setNama(this.fieldNamaSP.getText());
       arrTemp.add(model3);
       
       //head
       ModelHeadReport headReport = new ModelHeadReport();
       headReport.setNamaPemDaerah(this.NamaPemDaerahField.getText());
       headReport.setDinasDaerah(this.dinasDaerahField.getText());
       headReport.setAlamatDinas(this.alamatDinasField.getText());
       
       control.simpan(arrTemp,headReport);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldNipDP = new javax.swing.JTextField();
        fieldNipBP = new javax.swing.JTextField();
        fieldNipSP = new javax.swing.JTextField();
        fieldNamaDP = new javax.swing.JTextField();
        fieldNamaBP = new javax.swing.JTextField();
        fieldNamaSP = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        alamatDinasField = new javax.swing.JTextField();
        dinasDaerahField = new javax.swing.JTextField();
        NamaPemDaerahField = new javax.swing.JTextField();
        lblDP1 = new javax.swing.JLabel();
        lblDP2 = new javax.swing.JLabel();
        lblDP3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblBP = new javax.swing.JTextField();
        lblDP = new javax.swing.JTextField();
        lblSP = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kelola Report");

        jLabel1.setText("Jabatan");

        jLabel2.setText("NIP");

        jLabel3.setText("Nama");

        fieldNipDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNipDPActionPerformed(evt);
            }
        });

        fieldNamaBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNamaBPActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        alamatDinasField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatDinasFieldActionPerformed(evt);
            }
        });

        NamaPemDaerahField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaPemDaerahFieldActionPerformed(evt);
            }
        });

        lblDP1.setText("Nama Pemerintah Daerah");

        lblDP2.setText("Dinas Daerah");

        lblDP3.setText("Alamat Kantor Dinas");

        jLabel4.setText("Header Report");

        lblBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblBPActionPerformed(evt);
            }
        });

        lblDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblDPActionPerformed(evt);
            }
        });

        lblSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSimpan))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDP1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDP3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDP, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(lblBP, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSP, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NamaPemDaerahField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dinasDaerahField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldNipBP, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(fieldNipSP, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fieldNipDP, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(fieldNamaBP, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                        .addComponent(fieldNamaSP))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(fieldNamaDP)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))))
                            .addComponent(alamatDinasField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaPemDaerahField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDP1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dinasDaerahField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDP2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alamatDinasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDP3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNipDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNamaDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNipBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNamaBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNipSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNamaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSimpan)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNipDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNipDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNipDPActionPerformed

    private void fieldNamaBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNamaBPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNamaBPActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        this.Simpan();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void NamaPemDaerahFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaPemDaerahFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaPemDaerahFieldActionPerformed

    private void alamatDinasFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatDinasFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatDinasFieldActionPerformed

    private void lblBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblBPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBPActionPerformed

    private void lblDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDPActionPerformed

    private void lblSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NamaPemDaerahField;
    private javax.swing.JTextField alamatDinasField;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JTextField dinasDaerahField;
    private javax.swing.JTextField fieldNamaBP;
    private javax.swing.JTextField fieldNamaDP;
    private javax.swing.JTextField fieldNamaSP;
    private javax.swing.JTextField fieldNipBP;
    private javax.swing.JTextField fieldNipDP;
    private javax.swing.JTextField fieldNipSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField lblBP;
    private javax.swing.JTextField lblDP;
    private javax.swing.JLabel lblDP1;
    private javax.swing.JLabel lblDP2;
    private javax.swing.JLabel lblDP3;
    private javax.swing.JTextField lblSP;
    // End of variables declaration//GEN-END:variables
}
