/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package id.co.meda.apit.visual.form;

import id.co.meda.apit.enggine.penilaian.khusus.tower.Tower;
import id.co.meda.apit.visual.controller.ControlTower;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author PT. Data Bumi Indonesia
 */
public class FrmLspopTower extends javax.swing.JDialog {

    /**
     * Creates new form FrmLspopTower
     */
    public FrmLspopTower(java.awt.Frame parent, boolean modal, String nop) {
        super(parent, modal);
        initComponents();
        this.nop=nop;
        this.kdEdit=0;
        inisiasiAwal();
    }

    public FrmLspopTower(java.awt.Frame parent, boolean modal, String nop, Integer kdEdit, String bngKe) {
        super(parent, modal);
        initComponents();
        this.nop=nop;
        this.kdEdit=kdEdit;
        this.bngKe=bngKe;
        inisiasiAwal();
        txtBngKe.setText(this.bngKe);
    }
    
    private void inisiasiAwal() {
        formatAngka();
        String tmpNop = nop.substring(0,2)+"."+nop.substring(2,4)+"."+nop.substring(4,7)+
                "."+nop.substring(7,10)+"."+nop.substring(10,13)+"-"+nop.substring(13,17)+"."+nop.substring(17,18);
        lbNop.setText(tmpNop);
        elementsControl(kdEdit);
        if (kdEdit==1) {
            ambilData();
        }
    }
    
    private void ambilData() {
        tower = new Tower();
        ctrl.ambilTower(nop, bngKe, tower);
        txtThnBangun.setText(tower.getThnBangun());
        txtThnRenov.setText(tower.getThnRenov());
        cbKondisi.setSelectedItem(tower.getKondisi()); 
        txtTinggi.setText(tower.getTinggi().toString());
        cbTipe.setSelectedItem(tower.getTipe()); 
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBngKe = new javax.swing.JTextField();
        lbNop = new javax.swing.JLabel();
        txtThnBangun = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtThnRenov = new javax.swing.JTextField();
        cbTipe = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTinggi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btSimpan = new javax.swing.JButton();
        lbStatus = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbKondisi = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Data Tower");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("NOP");

        jLabel2.setText("Bangunan Ke");

        txtBngKe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBngKeKeyPressed(evt);
            }
        });

        lbNop.setForeground(new java.awt.Color(255, 0, 0));
        lbNop.setText("-");

        txtThnBangun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtThnBangunKeyPressed(evt);
            }
        });

        jLabel3.setText("Tahun Dibangun");

        jLabel4.setText("Tahun Renovasi");

        txtThnRenov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtThnRenovKeyPressed(evt);
            }
        });

        cbTipe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SST", "Greenfield" }));

        jLabel5.setText("Tipe");

        jLabel6.setText("Tinggi");

        txtTinggi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTinggiKeyPressed(evt);
            }
        });

        jLabel7.setText("meter");

        btSimpan.setText("Simpan");
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });

        lbStatus.setText("-");

        jLabel8.setText("Kondisi Umum");

        cbKondisi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sangat Baik", "Baik", "Sedang", "Jelek" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(lbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btSimpan)
                            .addComponent(cbTipe, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addComponent(cbKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThnRenov, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThnBangun, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBngKe, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNop, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbNop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(txtBngKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtThnBangun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtThnRenov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSimpan)
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void formatAngka() {
        ToolsFrm.setTextFilterNumber(txtBngKe, "\\D++");
        ToolsFrm.setTextFilterNumber(txtThnBangun, "\\D++");
        ToolsFrm.setTextFilterNumber(txtThnRenov, "\\D++");
        ToolsFrm.setTextFilterNumber(txtTinggi, "\\D++");
    }
    
    private void txtBngKeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBngKeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            //txtBngKe.toString().
            txtBngKe.setText(String.format("%3s",txtBngKe.getText()).replace(" ", "0").substring(0, 3));
            
            if (!txtBngKe.getText().equals("000")) {
                if (ctrl.cekNoBng(nop, txtBngKe.getText())) {
                    int reply = JOptionPane.showConfirmDialog(this, "Nomor bangunan : " + txtBngKe.getText()
                        + " sudah ada, apakah akan dilakukan pemutakhiran data ?",
                        "Konfirmasi Nomor Bangunan", JOptionPane.YES_NO_OPTION);

                    if (reply == JOptionPane.YES_OPTION) {
                        this.bngKe = txtBngKe.getText();
                        this.kdEdit = 1;
                        ambilData();
                        elementsControl(1);
                    } else {
                        txtBngKe.setText("");
                    }
                } else {
                    txtThnBangun.setEnabled(true);
                    txtThnRenov.setEnabled(true);
                    cbKondisi.setEnabled(true);
                    txtTinggi.setEnabled(true);
                    cbTipe.setEnabled(true);
                    txtThnBangun.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_txtBngKeKeyPressed

    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        FrmEditLspopTower tower = new FrmEditLspopTower(new JFrame(),true);
        tower.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void txtThnBangunKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtThnBangunKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThnBangunKeyPressed

    private void txtThnRenovKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtThnRenovKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThnRenovKeyPressed

    private void txtTinggiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTinggiKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTinggiKeyPressed

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
        // TODO add your handling code here:
        bngKe = txtBngKe.getText();
        if (!(bngKe.equals("") || bngKe.equals("000"))) {
            if (!cekTipeTower()) {
                JOptionPane.showMessageDialog(this, "Inputan tinggi dan tipe tower tidak cocok, silahkan diperbaiki !!!");
            } else {
                tower = new Tower();
                tower.setNop(nop);
                tower.setNoBng(bngKe);
                tower.setThnBangun(txtThnBangun.getText());
                tower.setThnRenov(txtThnRenov.getText());
                tower.setKondisi(cbKondisi.getSelectedItem().toString());
                tower.setTipe(cbTipe.getSelectedItem().toString());
                tower.setTinggi(Integer.parseInt((txtTinggi.getText().equals(""))?"0":txtTinggi.getText()));
                tower.setJmlKaki(4);
                tower.setKonstruksi("baja");
                tower.setPemasangan("di atas tanah");
                String status = ctrl.simpanData(kdEdit,tower);

                if (status.equals("ok")) { 
                    JOptionPane.showMessageDialog(this, "Simpan data berhasil");
                } else {
                    JOptionPane.showMessageDialog(this, "Simpan data gagal !!!");
                }

                this.setVisible(false);
                FrmEditLspopTower frm = new FrmEditLspopTower(new JFrame(), true);
                frm.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nomor bangunan harus diisi !!!");
            txtBngKe.requestFocus();
        }
    }//GEN-LAST:event_btSimpanActionPerformed
    
    private boolean cekTipeTower() {
        Integer tinggi = Integer.parseInt((txtTinggi.getText().equals(""))?"0":txtTinggi.getText());
        String tipe = cbTipe.getSelectedItem().toString();
        return (tinggi <= 100 || !tipe.equals("SST")) && (tinggi >= 101 || !tipe.equals("Greenfield"));
        
    }
    
    private void elementsControl(Integer kode) {
        if (kode==0) {
            lbStatus.setText("Perekaman Data Baru");
            txtBngKe.setEnabled(true);
            txtThnBangun.setEnabled(false);
            txtThnRenov.setEnabled(false);
            txtTinggi.setEnabled(false);
            cbTipe.setEnabled(false);
            cbKondisi.setEnabled(false);
        } else if (kode==1) {
            lbStatus.setText("Pemutakhiran Data");
            txtBngKe.setEnabled(false);
            txtThnBangun.setEnabled(true);
            txtThnRenov.setEnabled(true);
            txtTinggi.setEnabled(true);
            cbTipe.setEnabled(true);
            cbKondisi.setEnabled(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSimpan;
    private javax.swing.JComboBox cbKondisi;
    private javax.swing.JComboBox cbTipe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbNop;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JTextField txtBngKe;
    private javax.swing.JTextField txtThnBangun;
    private javax.swing.JTextField txtThnRenov;
    private javax.swing.JTextField txtTinggi;
    // End of variables declaration//GEN-END:variables
    
    private final ControlTower ctrl = new ControlTower();
    private Integer kdEdit; //nilai : 0 = insert; 1=update; 2=delete
    private String bngKe; 
    private String nop; //
    private Tower tower;
}
