/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package id.co.meda.apit.visual.form;

import id.co.meda.apit.enggine.penilaian.khusus.pelabuhan.ItemAnalisisHargaSatuan;
import id.co.meda.apit.enggine.penilaian.khusus.pelabuhan.SpopPelabuhan;
import id.co.meda.apit.visual.controller.ControlFrmPenilaianPelabuhan;
import id.co.meda.apit.visual.report.LaporanCrnPelabuhan;
import id.co.meda.apit.visual.report.TampilkanReportPelabuhan;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author PT. Databumi Indonesia
 */
public class FrmPenilaianPelabuhan extends javax.swing.JDialog {

    private ControlFrmPenilaianPelabuhan control = new ControlFrmPenilaianPelabuhan();
    private int totalCRN = 0;
    
    /**
     * Creates new form FrmPenilaianPelabuhan
     */
    public FrmPenilaianPelabuhan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        hitungCrnBtn.setEnabled(false);
        tahunField.setEnabled(false);
        ToolsFrm.setTextFilterNumber(tahunField, "\\D++");
        this.checkHrgTerakhir.setEnabled(false);
        this.btnCetak.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        checkHrgTerakhir = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCrn = new javax.swing.JTable(control.getModelTableCRN("", "")){

            public Component prepareRenderer(TableCellRenderer render,
                int indexRow, int indexCol)
            {
                Component comp = super.prepareRenderer(render, indexRow, indexCol);
                if(indexRow == 0 || indexRow == 3 || indexRow == 10 || indexRow == 13)
                {
                    comp.setBackground(Color.BLUE);
                    comp.setForeground(Color.WHITE);

                }else if(isCellSelected(indexRow,indexCol)){

                    comp.setBackground(Color.YELLOW);
                    comp.setForeground(Color.BLACK);
                }else
                {
                    comp.setBackground(Color.CYAN);
                    comp.setForeground(Color.BLACK);
                }
                return comp;
            }

        };
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCRN = new javax.swing.JLabel();
        txtNop = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hitungCrnBtn = new javax.swing.JButton();
        lblNamaPelabuhan = new javax.swing.JLabel();
        lblJnsPelabuhan = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tahunField = new javax.swing.JTextField();
        btnCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Penilaian Pelabuhan");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        checkHrgTerakhir.setText("Gunakan data penilaian terakhir");
        checkHrgTerakhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkHrgTerakhirActionPerformed(evt);
            }
        });

        tableCrn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableCrn);

        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setText("Nilai CRN");

        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setText(":");

        lblCRN.setForeground(new java.awt.Color(0, 153, 0));
        lblCRN.setText("Rp");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(checkHrgTerakhir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCRN, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkHrgTerakhir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(lblCRN))
                .addContainerGap())
        );
        jLayeredPane1.setLayer(checkHrgTerakhir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblCRN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        try {
            txtNop.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##.###.###.###-####.#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNopActionPerformed(evt);
            }
        });
        txtNop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNopKeyPressed(evt);
            }
        });

        jLabel1.setText("NOP");

        jLabel2.setText("Nama Pelabuhan");

        jLabel3.setText("Jenis Pelabuhan");

        jLabel4.setText("Tahun Penilaian");

        hitungCrnBtn.setText("Hitung & Simpan CRN");
        hitungCrnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungCrnBtnActionPerformed(evt);
            }
        });

        lblNamaPelabuhan.setForeground(new java.awt.Color(0, 0, 204));
        lblNamaPelabuhan.setText("-");

        lblJnsPelabuhan.setForeground(new java.awt.Color(0, 0, 204));
        lblJnsPelabuhan.setText("-");

        jLabel8.setText(":");

        jLabel9.setText(":");

        jLabel10.setText(":");

        jLabel11.setText(":");

        tahunField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tahunFieldKeyPressed(evt);
            }
        });

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNop, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 7, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tahunField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(hitungCrnBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCetak))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNamaPelabuhan, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblJnsPelabuhan, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblNamaPelabuhan)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblJnsPelabuhan)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hitungCrnBtn)
                    .addComponent(jLabel11)
                    .addComponent(tahunField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCetak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNopActionPerformed

    private void txtNopKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNopKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String tmpNop = txtNop.getText().replace(".", "").replace("-", "");
            
            if(control.cekNop(tmpNop))
            {
                 SpopPelabuhan spop = control.getSpop(tmpNop);
                 this.lblNamaPelabuhan.setText(spop.getNamaPelabuhan());
                 this.lblJnsPelabuhan.setText(spop.getJenisPelabuhan());
                 
                 tahunField.setEnabled(true);
            }else
            {
                 JOptionPane.showMessageDialog(this, "NOP tidak ditemukan !!!");
                 txtNop.setText("");
                 tahunField.setEnabled(false);
            }
            
        }
    }//GEN-LAST:event_txtNopKeyPressed

    private void hitungCrnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungCrnBtnActionPerformed
        // TODO add your handling code here:
        this.hitungCRN(true);   
    }//GEN-LAST:event_hitungCrnBtnActionPerformed

    private void tahunFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tahunFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String tmpNop = txtNop.getText().replace(".", "").replace("-", "");
            String tahun = this.tahunField.getText();
            
            
            if(control.cekTahunPenilaian(tmpNop, tahun))
            {
                hitungCrnBtn.setEnabled(true);
                this.checkHrgTerakhir.setEnabled(false);
                this.inisiasiTableCrn(tmpNop, tahun);
                this.btnCetak.setEnabled(true);
            }else
            {
                 int reply = JOptionPane.showConfirmDialog(rootPane, "NOP "+tmpNop+""
                         + " belum pernah melakukan penilaian pada tahun "+tahun+". Apakah "
                         + "anda ingin melakukan penilaian?", 
                       "Konfirmasi Penilaian", JOptionPane.YES_NO_OPTION,0, null);
                if(reply == JOptionPane.YES_OPTION)
                {
                    this.checkHrgTerakhir.setEnabled(true);
                    hitungCrnBtn.setEnabled(true);
                    this.btnCetak.setEnabled(true);
                    this.inisiasiTableCrn(tmpNop, tahun);
            
                }else
                {
                    this.checkHrgTerakhir.setEnabled(false);
                    hitungCrnBtn.setEnabled(false);
                    this.tahunField.setText("");
                    this.btnCetak.setEnabled(false);
                }
            }
            
        }
    }//GEN-LAST:event_tahunFieldKeyPressed

    private void checkHrgTerakhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkHrgTerakhirActionPerformed
        // TODO add your handling code here:
        if(this.checkHrgTerakhir.isSelected())
        {
            String tmpNop = txtNop.getText().replace(".", "").replace("-", "");
            String tahun = control.getPenilTerakhir();
            this.inisiasiTableCrn(tmpNop, tahun);
            
        }else
        {
            String tmpNop = txtNop.getText().replace(".", "").replace("-", "");
            String tahun = this.tahunField.getText();
            this.inisiasiTableCrn(tmpNop, tahun);
        }
    }//GEN-LAST:event_checkHrgTerakhirActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
         String nop = txtNop.getText().replace(".", "").replace("-", "");
         String tahun = this.tahunField.getText();
            
         ArrayList<LaporanCrnPelabuhan> arrCrn = this.isiReport();
         DecimalFormat df2 = new DecimalFormat( "#,###,###,##0.00" );
         String hrgCrn = "Rp "+df2.format(totalCRN);
         TampilkanReportPelabuhan report = new TampilkanReportPelabuhan(nop,tahun, arrCrn,hrgCrn);
         report.tampilkanReportPelabuhan();
         
    }//GEN-LAST:event_btnCetakActionPerformed

    private ArrayList<LaporanCrnPelabuhan> isiReport()
    {
        int tempNum = tableCrn.getModel().getRowCount();
        ArrayList<LaporanCrnPelabuhan> arrCrn = new ArrayList<LaporanCrnPelabuhan>();
        
        for(int i = 0; i < tempNum; i++)
        {
            LaporanCrnPelabuhan temp = new LaporanCrnPelabuhan();
            temp.setJenisPekerjaan(tableCrn.getValueAt(i, 0)+"");
            temp.setSatuan(tableCrn.getValueAt(i, 1)+"");
            temp.setVolume(tableCrn.getValueAt(i, 2)+"");
            temp.setHrg_bahan(tableCrn.getValueAt(i, 3)+"");
            temp.setHrg_upah(tableCrn.getValueAt(i, 4)+"");
            temp.setHrg_jumlah(tableCrn.getValueAt(i, 5)+"");
            temp.setHrg_total(tableCrn.getValueAt(i, 6)+"");
            
            arrCrn.add(temp);
        }
        
        return arrCrn;
    }
    
    private void inisiasiTableCrn(String nop,String tahun)
    {
            this.tableCrn.setModel(control.getModelTableCRN(nop, tahun));
            this.tableCrn.removeColumn(this.tableCrn.getColumnModel().getColumn(0));
            this.tableCrn.getColumnModel().getColumn(0).setPreferredWidth(150);
            this.tableCrn.getColumnModel().getColumn(1).setPreferredWidth(50);
            this.tableCrn.getColumnModel().getColumn(0).setResizable(false);
            this.tableCrn.getColumnModel().getColumn(1).setResizable(false);
            
            hitungCRN(false);
    }
    
    //saveCheck : sekaligus disimpan atau tidak (true : simpan , false : tidak)
    private void hitungCRN(boolean saveCheck)
    {
        totalCRN = 0;
        int rowSize = this.tableCrn.getModel().getRowCount();
        
        ArrayList<ItemAnalisisHargaSatuan> arrItem = new ArrayList<ItemAnalisisHargaSatuan>();
        
        for(int i = 0; i < rowSize; i++)
        {
            ItemAnalisisHargaSatuan item = new ItemAnalisisHargaSatuan();
            
           if(i == 0 || i == 3 || i == 10 || i == 13)
           {
               
               item.setId((String)this.tableCrn.getModel().getValueAt(i, 0));
               item.setJenisPekerjaan((String)this.tableCrn.getModel().getValueAt(i, 1));
               item.setSatuan("");
               item.setVolume(0.0);
               item.setHrg_bahan(0.0);
               item.setHrg_upah(0.0);
               item.setHrg_jumlah(0.0);
               item.setHrg_total(0.0);
               
               arrItem.add(item);
           }else
           {
                double vol = (double) this.tableCrn.getModel().getValueAt(i, 3);
                double hrg_bahan = (double) this.tableCrn.getModel().getValueAt(i, 4);
                double hrg_upah = (double) this.tableCrn.getModel().getValueAt(i, 5);
                double hrg_jumlah = hrg_bahan + hrg_upah;
                double hrg_total = hrg_jumlah*vol;
                
                totalCRN += hrg_total;
                
                this.tableCrn.getModel().setValueAt(hrg_jumlah, i, 6);
                this.tableCrn.getModel().setValueAt(hrg_total, i, 7);
                
                item.setId((String)this.tableCrn.getModel().getValueAt(i, 0));
                item.setJenisPekerjaan((String)this.tableCrn.getModel().getValueAt(i, 1));
                item.setSatuan((String)this.tableCrn.getModel().getValueAt(i, 2));
                item.setVolume((double)this.tableCrn.getModel().getValueAt(i, 3));
                item.setHrg_bahan((double)this.tableCrn.getModel().getValueAt(i, 4));
                item.setHrg_upah((double)this.tableCrn.getModel().getValueAt(i, 5));
                item.setHrg_jumlah((double)this.tableCrn.getModel().getValueAt(i, 6));
                item.setHrg_total((double)this.tableCrn.getModel().getValueAt(i, 7));
                
                arrItem.add(item);
           }
        }
        
        DecimalFormat df2 = new DecimalFormat( "#,###,###,##0.00" );
        this.lblCRN.setText("Rp "+df2.format(totalCRN));
        
        String tmpNop = txtNop.getText().replace(".", "").replace("-", "");
        String tahun = this.tahunField.getText();
            
        if(saveCheck)
        {
            if(control.simpanCrn(arrItem, tmpNop, tahun))
            {
                JOptionPane.showMessageDialog(rootPane, "Perhitungan CRN berhasil disimpan", "Perhitungan CRN"
                        , JOptionPane.INFORMATION_MESSAGE);

            }else
            {
                JOptionPane.showMessageDialog(rootPane, "Perhitungan CRN gagal disimpan", "Perhitungan CRN"
                        , JOptionPane.ERROR_MESSAGE);

            }
        }
    
    }
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JCheckBox checkHrgTerakhir;
    private javax.swing.JButton hitungCrnBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCRN;
    private javax.swing.JLabel lblJnsPelabuhan;
    private javax.swing.JLabel lblNamaPelabuhan;
    private javax.swing.JTable tableCrn;
    private javax.swing.JTextField tahunField;
    private javax.swing.JFormattedTextField txtNop;
    // End of variables declaration//GEN-END:variables
}
