/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package id.co.meda.apit.visual.form;

import id.co.meda.apit.visual.controller.ControlPengguna;
import id.co.meda.apit.visual.controller.Pengguna;
import id.co.meda.apit.visual.controller.SecEncryptDecrypt;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author PT. Data Bumi Indonesia
 */
public class FrmPengguna extends javax.swing.JDialog {

    /**
     * Creates new form FrmPengguna
     */
    public FrmPengguna(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.kdEdit=0;
        inisiasiAwal();
    }

    /**
     * Creates new form FrmPengguna
     */
    public FrmPengguna(java.awt.Frame parent, boolean modal, Integer kdEdit, String idPengguna) {
        super(parent, modal);
        initComponents();
        this.kdEdit=kdEdit;
        this.idPengguna=idPengguna;
        inisiasiAwal();
    }
    
    private void inisiasiAwal() {
        pengguna = new Pengguna();
        ctrlPeng.ambilWenang(cbKewenangan);
        isiData();
    }
    
    private void isiData() {
        if (kdEdit==1) {
            pengguna = ctrlPeng.ambilPengguna(idPengguna);
            txtUser.setText(pengguna.getNmUser());
            txtNip.setText(pengguna.getNip());
            txtNmLkp.setText(pengguna.getNmLengkap());
            cbKewenangan.setSelectedItem(pengguna.getKdRole()+" - "+ ctrlPeng.ambilNmRole(pengguna.getKdRole()));

        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNmLkp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNip = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbKewenangan = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txtPwd = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txtPwdKonf = new javax.swing.JPasswordField();
        btSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Pengguna");

        txtNmLkp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNmLkpActionPerformed(evt);
            }
        });

        jLabel5.setText("Kewenangan");

        jLabel4.setText("Nama Lengkap");

        jLabel3.setText("NIP");

        jLabel2.setText("User");

        jLabel6.setText("Password");

        jLabel7.setText("Konfirmasi");

        btSimpan.setText("Simpan");
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNip, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNmLkp, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbKewenangan, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btSimpan)
                            .addComponent(txtPwdKonf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNmLkp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbKewenangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPwdKonf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSimpan)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNmLkpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNmLkpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNmLkpActionPerformed

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
        // TODO add your handling code here:
        if (txtUser.getText().length()>0) {
            boolean kdLanjut = true;
            if (kdEdit>0) { pengguna.setIdUser(Integer.parseInt(idPengguna)); }
            pengguna.setNmUser((txtUser.getText().length()>0)?txtUser.getText():"-");
            pengguna.setNip((txtNip.getText().length()>0)?txtNip.getText():"-");
            pengguna.setNmLengkap((txtNmLkp.getText().length()>0)?txtNmLkp.getText():"-");
            pengguna.setKdRole(cbKewenangan.getSelectedItem().toString().substring(0, 2));

            String pwd = new String(txtPwd.getPassword());
            String pwdKonf = new String(txtPwdKonf.getPassword());

            if (pwd.length()>0) {
                if (pwd.equals(pwdKonf)) {
                    pengguna.setPwd(SecEncryptDecrypt.EncryptText(pwd));
                } else {
                    JOptionPane.showMessageDialog(this, "Password berbeda dengan konfirmasi ...");
                    txtPwd.setText(""); txtPwdKonf.setText("");
                    txtPwd.requestFocus();
                    kdLanjut = false;
                }
            }

            if (kdLanjut) {
                String pesan = ctrlPeng.simpanPengguna(kdEdit, pengguna);
                if (pesan.equals("ok")) {
                    JOptionPane.showMessageDialog(this, "Simpan data berhasil ...");
                } else {
                    JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat proses simpan, pesan : " + pesan);
                }
             this.setVisible(false);
             FrmEditPengguna frmEdit = new FrmEditPengguna(new JFrame(), true);
             frmEdit.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Minimal nama user harus diisi !!!!");
            txtUser.requestFocus();
        }
    }//GEN-LAST:event_btSimpanActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSimpan;
    private javax.swing.JComboBox cbKewenangan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtNip;
    private javax.swing.JTextField txtNmLkp;
    private javax.swing.JPasswordField txtPwd;
    private javax.swing.JPasswordField txtPwdKonf;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    private Integer kdEdit;
    private String idPengguna;
    private Pengguna pengguna;
    final private ControlPengguna ctrlPeng = new ControlPengguna();
}
