/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package id.co.meda.apit.visual.form;

import id.co.meda.apit.enggine.penilaian.khusus.tower.NilaiTower;
import id.co.meda.apit.enggine.penilaian.khusus.tower.PenilaianTower;
import id.co.meda.apit.enggine.penilaian.khusus.tower.Tower;
import id.co.meda.apit.enggine.penilaian.model.Spop;
import id.co.meda.apit.visual.controller.ControlPenilaianTower;
import id.co.meda.apit.visual.report.LaporanPenilaianTower;
import id.co.meda.apit.visual.report.TampilkanReportTower;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author PT. Data Bumi Indonesia
 */
public class FrmPenilaianTower extends javax.swing.JDialog {

    /**
     * Creates new form FrmPenilaianTower
     */
    public FrmPenilaianTower(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inisiasiAwal();
    }

    private void inisiasiAwal() {
        ctrl.isiCbTahun(cbThnPenilaian);
        //set selected year-----------------///
        Date date = new Date();
        Calendar cal = Calendar.getInstance();
        cal.setTime(date);
        String year = cal.get(Calendar.YEAR)+"";
        
        cbThnPenilaian.setSelectedItem(year);
        //---------------------------------///
        isiGrid(0);
    }
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNop = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        cbThnPenilaian = new javax.swing.JComboBox();
        lbNmWp = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTower = new javax.swing.JTable();
        btProsesPenil = new javax.swing.JButton();
        btCetak = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Penilaian Tower");

        jLabel2.setText("Nama WP");

        jLabel1.setText("NOP");

        try {
            txtNop.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##.###.###.###-####.#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNopKeyPressed(evt);
            }
        });

        jLabel4.setText("Tahun Penilaian");

        cbThnPenilaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbThnPenilaianActionPerformed(evt);
            }
        });

        lbNmWp.setBackground(new java.awt.Color(255, 255, 255));
        lbNmWp.setForeground(new java.awt.Color(255, 0, 0));
        lbNmWp.setText("-");

        tblTower.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTower);

        btProsesPenil.setText("Proses Penilaian");
        btProsesPenil.setEnabled(false);
        btProsesPenil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProsesPenilActionPerformed(evt);
            }
        });

        btCetak.setText("Lihat / Cetak");
        btCetak.setEnabled(false);
        btCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btProsesPenil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCetak)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btProsesPenil)
                    .addComponent(btCetak))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tower", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Bangunan Lain", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbThnPenilaian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNmWp, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNop, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbNmWp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbThnPenilaian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNopKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNopKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            nop = txtNop.getText().replace(".","").replace("-","");
            cariNop();
            isiGrid(1);
        }
    }//GEN-LAST:event_txtNopKeyPressed

    private void btProsesPenilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProsesPenilActionPerformed
        // TODO add your handling code here:
        thnPenilaian = cbThnPenilaian.getSelectedItem().toString();
        
        try {
            if (ctrl.cekHslPenilaian(nop, thnPenilaian)) {
                if (JOptionPane.showConfirmDialog(this, "NOP "+nop+" untuk tahun "
                  +thnPenilaian+" sudah pernah dilakukan penilaian, apakah dilakukan penilaian ulang ?", 
                   "Konfirmasi Proses Penilaian", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
                    prosesPenilaian();
                }
            } else {
                prosesPenilaian();
            }
        } catch (Exception e) {}
    }//GEN-LAST:event_btProsesPenilActionPerformed

    private void btCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCetakActionPerformed
        // TODO add your handling code here:
        ArrayList<Tower> listTower = ctrl.isiListTower(nop);
        ArrayList<NilaiTower> listNilaiTower = ctrl.isiListNilaiTower(nop, thnPenilaian);
        
        TampilkanReportTower rep = new TampilkanReportTower(spop, listTower, listNilaiTower);
        rep.tampilReport();
    }//GEN-LAST:event_btCetakActionPerformed

    private void cbThnPenilaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbThnPenilaianActionPerformed
        // TODO add your handling code here:
        thnPenilaian = cbThnPenilaian.getSelectedItem().toString();
    }//GEN-LAST:event_cbThnPenilaianActionPerformed
    
    private void prosesPenilaian() {
        btProsesPenil.setEnabled(false);
        PenilaianTower penil = new PenilaianTower(nop, thnPenilaian);
        penil.mulaiPenilaian();
        JOptionPane.showMessageDialog(this, "Proses penilaian telah selesai dilakukan ...");
        btProsesPenil.setEnabled(true);
    }
    
    private void cariNop() {
        spop = new Spop();
        ctrl.cariNop(nop, spop);
        
        if (spop.getNop()!=null && ctrl.cekBngDiLspop(nop)) {
            lbNmWp.setText(spop.getNamaWp());
            btProsesPenil.setEnabled(true);
            btCetak.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "NOP tidak ditemukan atau tidak memiliki bangunan !!!");
            txtNop.setText("");
            lbNmWp.setText("");
            btProsesPenil.setEnabled(false);
            btCetak.setEnabled(false);
        }
    }
    private void isiGrid(int kode) {
        if (kode==0) {
            tblTower.setModel(ctrl.getTableModel());
        } else {
            tblTower.setModel(ctrl.getTableModel(nop));
        }
        tblTower.getColumnModel().getColumn(0).setPreferredWidth(5);        
        tblTower.getColumnModel().getColumn(1).setPreferredWidth(150);        
        tblTower.getColumnModel().getColumn(2).setPreferredWidth(50);        
        tblTower.setRowHeight(35);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCetak;
    private javax.swing.JButton btProsesPenil;
    private javax.swing.JComboBox cbThnPenilaian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbNmWp;
    private javax.swing.JTable tblTower;
    private javax.swing.JFormattedTextField txtNop;
    // End of variables declaration//GEN-END:variables
    private final ControlPenilaianTower ctrl = new ControlPenilaianTower();
    private String nop;
    private Spop spop;
    private String thnPenilaian;
}
