/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package id.co.meda.apit.visual.form;

import id.co.meda.apit.visual.controller.ControlProsesPenilaianPerikanan;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PT. Databumi Indonesia
 */
public class FrmPenilaianPerikanan extends javax.swing.JDialog {
    
    private ControlProsesPenilaianPerikanan control = new ControlProsesPenilaianPerikanan();
    /**
     * Creates new form ProsesPenilaianPerikanan
     */
    public FrmPenilaianPerikanan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inisiasiTableTanah("","");
        inisiasiTableBangunan("","");
        inisiasiTablePerikanan("","");
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabPane = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableTanah = new javax.swing.JTable();
        labelNjopTanah = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCetakTanah = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableBangunan = new javax.swing.JTable();
        labelNjopBangunan = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nilaiBngBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnCetakBangunan = new javax.swing.JButton();
        btnCetakNjop = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        labelLuasTot = new javax.swing.JLabel();
        labelNilaiTot = new javax.swing.JLabel();
        labelKelasBng = new javax.swing.JLabel();
        labelNilaiPerM2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePerikanan = new javax.swing.JTable()
        ;
        jLabel8 = new javax.swing.JLabel();
        labelNjopPerikanan = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnCetakIkan = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnCetakRingkasan = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblNjopTanahR = new javax.swing.JLabel();
        lblNjopBangunanR = new javax.swing.JLabel();
        lblNjopPerikananR = new javax.swing.JLabel();
        lblNjopTotalR = new javax.swing.JLabel();
        txtNop = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        labelPemilik = new javax.swing.JLabel();
        cbTahunPenilaian = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Proses Penilaian Perikanan");

        jLabel1.setText("NOP");

        tableTanah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tableTanah);

        labelNjopTanah.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        labelNjopTanah.setForeground(new java.awt.Color(0, 153, 0));
        labelNjopTanah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNjopTanah.setText("Rp. -");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("NJOP Tanah");

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setText(":");

        btnCetakTanah.setText("Cetak");
        btnCetakTanah.setEnabled(false);
        btnCetakTanah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakTanahActionPerformed(evt);
            }
        });

        jLabel23.setForeground(new java.awt.Color(0, 51, 255));
        jLabel23.setText("*klik 2 kali pada kolom NIR untuk input nilai NIR");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(697, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelNjopTanah, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCetakTanah)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCetakTanah, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(labelNjopTanah))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        tabPane.addTab("Tanah", jPanel3);

        tableBangunan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tableBangunan);

        labelNjopBangunan.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        labelNjopBangunan.setForeground(new java.awt.Color(0, 153, 0));
        labelNjopBangunan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNjopBangunan.setText("Rp. -");
        labelNjopBangunan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 0));
        jLabel7.setText(":");

        nilaiBngBtn.setText("Proses Nilai Bangunan");
        nilaiBngBtn.setEnabled(false);
        nilaiBngBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiBngBtnActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 0));
        jLabel10.setText("Luas Total (M2)");

        btnCetakBangunan.setText("Cetak Nilai Bangunan");
        btnCetakBangunan.setEnabled(false);
        btnCetakBangunan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakBangunanActionPerformed(evt);
            }
        });

        btnCetakNjop.setText("Cetak NJOP");
        btnCetakNjop.setEnabled(false);
        btnCetakNjop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakNjopActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 153, 0));
        jLabel24.setText("NJOP Bangunan");

        jLabel25.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 153, 0));
        jLabel25.setText("Nilai Total (Rp)");

        jLabel26.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 153, 0));
        jLabel26.setText("Kelas Bangunan");

        jLabel27.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 153, 0));
        jLabel27.setText("Nilai Per M2 (Rp)");

        jLabel28.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 153, 0));
        jLabel28.setText(":");

        jLabel29.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 153, 0));
        jLabel29.setText(":");

        jLabel30.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 153, 0));
        jLabel30.setText(":");

        jLabel31.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 153, 0));
        jLabel31.setText(":");

        labelLuasTot.setForeground(new java.awt.Color(0, 153, 0));
        labelLuasTot.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelLuasTot.setText("-");

        labelNilaiTot.setForeground(new java.awt.Color(0, 153, 0));
        labelNilaiTot.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNilaiTot.setText("-");

        labelKelasBng.setForeground(new java.awt.Color(0, 153, 0));
        labelKelasBng.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelKelasBng.setText("-");

        labelNilaiPerM2.setForeground(new java.awt.Color(0, 153, 0));
        labelNilaiPerM2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNilaiPerM2.setText("-");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nilaiBngBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCetakBangunan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCetakNjop))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelLuasTot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelNilaiTot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelKelasBng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelNilaiPerM2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelNjopBangunan, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nilaiBngBtn)
                    .addComponent(btnCetakBangunan)
                    .addComponent(btnCetakNjop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7)
                    .addComponent(labelLuasTot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel28)
                    .addComponent(labelNilaiTot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel29)
                    .addComponent(labelKelasBng))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel30)
                    .addComponent(labelNilaiPerM2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel31)
                    .addComponent(labelNjopBangunan))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        tabPane.addTab("Bangunan", jPanel4);

        tablePerikanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablePerikanan);

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 0));
        jLabel8.setText("NJOP Wilayah Perikanan");

        labelNjopPerikanan.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        labelNjopPerikanan.setForeground(new java.awt.Color(0, 153, 0));
        labelNjopPerikanan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNjopPerikanan.setText("Rp. -");

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setText(":");

        btnCetakIkan.setText("Cetak");
        btnCetakIkan.setEnabled(false);
        btnCetakIkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakIkanActionPerformed(evt);
            }
        });

        jLabel32.setForeground(new java.awt.Color(0, 51, 255));
        jLabel32.setText("*klik 2 kali pada kolom Biaya Operasional untuk mengisi Biaya Operasional");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNjopPerikanan, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCetakIkan)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCetakIkan)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(labelNjopPerikanan)
                    .addComponent(jLabel9))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        tabPane.addTab("Wilayah Perikanan", jPanel1);

        jLabel6.setText("RINGKASAN PENILAIAN");

        jLabel11.setText("NJOP TANAH");

        jLabel12.setText("NJOP BANGUNAN");

        jLabel13.setText("NJOP WILAYAH PERIKANAN");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText(":");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText(":");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText(":");

        jLabel17.setText("NJOP WILAYAH PERIKANAN + NJOP TANAH + NJOP BANGUNAN");

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText(":");

        btnCetakRingkasan.setText("Cetak");
        btnCetakRingkasan.setEnabled(false);
        btnCetakRingkasan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakRingkasanActionPerformed(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(0, 153, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Rp.");

        jLabel20.setForeground(new java.awt.Color(0, 153, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Rp.");

        jLabel21.setForeground(new java.awt.Color(0, 153, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Rp.");

        jLabel22.setForeground(new java.awt.Color(0, 153, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Rp.");

        lblNjopTanahR.setForeground(new java.awt.Color(0, 153, 0));
        lblNjopTanahR.setText("0");

        lblNjopBangunanR.setForeground(new java.awt.Color(0, 153, 0));
        lblNjopBangunanR.setText("0");

        lblNjopPerikananR.setForeground(new java.awt.Color(0, 153, 0));
        lblNjopPerikananR.setText("0");

        lblNjopTotalR.setForeground(new java.awt.Color(0, 153, 0));
        lblNjopTotalR.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNjopTotalR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNjopBangunanR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNjopPerikananR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNjopTanahR, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 283, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCetakRingkasan)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnCetakRingkasan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(jLabel19)
                    .addComponent(lblNjopTanahR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel20)
                    .addComponent(lblNjopBangunanR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(jLabel21)
                    .addComponent(lblNjopPerikananR))
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel22)
                    .addComponent(lblNjopTotalR))
                .addContainerGap(188, Short.MAX_VALUE))
        );

        tabPane.addTab("Ringkasan Penilaian", jPanel5);

        try {
            txtNop.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##.###.###.###-####.#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNopActionPerformed(evt);
            }
        });
        txtNop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNopKeyPressed(evt);
            }
        });

        jLabel2.setText("Nama Pemilik");

        labelPemilik.setForeground(new java.awt.Color(0, 0, 204));
        labelPemilik.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPemilik.setText("-");

        cbTahunPenilaian.setEnabled(false);
        cbTahunPenilaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTahunPenilaianActionPerformed(evt);
            }
        });

        jLabel3.setText("Tahun Penilaian");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNop)
                            .addComponent(labelPemilik, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTahunPenilaian, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tabPane, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelPemilik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTahunPenilaian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(40, 40, 40)
                .addComponent(tabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNopActionPerformed

    private void txtNopKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNopKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String tmpNop = txtNop.getText().replace(".", "").replace("-", "");
            this.cbTahunPenilaian.setEnabled(true);
            control.isiCombo(cbTahunPenilaian);
            
            //mengisi label pemilik
            control.buatModel(tmpNop,"");
            if(control.getPendataan().getSpopIkan().getSpop().getNamaWp() != null )
            {
                this.labelPemilik.setText(control.getPendataan().getSpopIkan().getSpop().getNamaWp());
            
            //ubah kembali jadi 0
            control.setNjopTanah(0);
            control.setNjopBangunan(0);
            control.setNjopPerikanan(0);
            }else
            {
                  JOptionPane.showMessageDialog(this, "NOP tidak ditemukan di data SPOP atau LSPOP !!!");
                  txtNop.setText("");
                  this.cbTahunPenilaian.setEnabled(false);
            }
        }
          
    }//GEN-LAST:event_txtNopKeyPressed

    private void inisiasiTableTanah(String nop,String tahun)
    {
        final String tahun2 = tahun;
        final String nop2 = nop;
        this.tableTanah.setModel(control.getModelTableTanah(nop,tahun));
        this.tableTanah.removeColumn(tableTanah.getColumnModel().getColumn(6));
        
        DecimalFormat df2 = new DecimalFormat( "#,###,###,##0.00" );
        this.labelNjopTanah.setText("Rp "+df2.format(control.getNjopTanah())+"");
        this.lblNjopTanahR.setText(df2.format(control.getNjopTanah())+"");
        this.lblNjopTotalR.setText(df2.format(control.getTotalNJop())+"");
        
        this.tableTanah.getModel().addTableModelListener(new TableModelListener(){
             
             public void tableChanged(TableModelEvent e)
            {
                if(e.getType() == TableModelEvent.UPDATE)
                {
                    
                    String kodePeruntukan = (String)tableTanah.getModel().getValueAt(tableTanah.getSelectedRow(), 6);
                    double luas = (double)tableTanah.getValueAt(tableTanah.getSelectedRow(),1);
                    double nir = (double)tableTanah.getValueAt(tableTanah.getSelectedRow(), 2);
                    control.penilaianTanah(nop2, tahun2, kodePeruntukan, luas, nir);
                    control.prosesNjop(nop2, tahun2);
                    
                    //jadikan 0 kembali                    
                    control.setNjopTanah(0);
                    control.setNjopBangunan(0);
                    control.setNjopPerikanan(0);
            
                    inisiasiTableTanah(nop2,tahun2);
                    
                }
            }
        });
    
    }
    
    private void inisiasiTableBangunan(String nop,String tahun)
    {
       //hapus table
        DefaultTableModel temp = (DefaultTableModel)this.tableBangunan.getModel();
        temp.setRowCount(0);
        
        this.tableBangunan.setModel(temp);
        
       this.tableBangunan.setModel(control.getModelTableBangunan(nop, tahun));
       
       DecimalFormat df2 = new DecimalFormat( "#,###,###,##0.00" );
       this.labelNjopBangunan.setText("Rp "+df2.format(control.getNjopBangunan()));
       this.lblNjopBangunanR.setText(df2.format(control.getNjopBangunan())+"");
       this.lblNjopTotalR.setText(df2.format(control.getTotalNJop())+"");
       
       this.labelLuasTot.setText(df2.format(control.getTotalLuasBangunan())+"");
       this.labelNilaiTot.setText(df2.format(control.getTotalNilai())+"");
       this.labelNilaiPerM2.setText(df2.format(control.getNilaiPerM2())+"");
       this.labelKelasBng.setText(control.getKelas());
       this.labelNjopBangunan.setText("Rp "+df2.format(control.getNilaiKeseluruhan()));
    }
    
   private void inisiasiTablePerikanan(String nop,String tahun)
    {
        final String nop2 = nop;
        final String tahun2 = tahun;
        
       //hapus table
        DefaultTableModel temp = (DefaultTableModel)this.tablePerikanan.getModel();
        temp.setRowCount(0);
        
        this.tablePerikanan.setModel(temp);
        
        this.tablePerikanan.setModel(control.getModelTablePerikanan(nop, tahun));
       this.tablePerikanan.getModel().addTableModelListener(new TableModelListener(){
             
             public void tableChanged(TableModelEvent e)
            {
                if(e.getType() == TableModelEvent.UPDATE)
                {
                    String jenis = (String)tablePerikanan.getValueAt(tablePerikanan.getSelectedRow(),0);
                    double biayaOp = (double)tablePerikanan.getValueAt(tablePerikanan.getSelectedRow(),3);
                    control.penilaianPendapatanIkan(jenis,biayaOp);
                    inisiasiTablePerikanan(nop2,tahun2);
                    
                }
            }
        });
               
       
       DecimalFormat df2 = new DecimalFormat( "#,###,###,##0.00" );
       this.labelNjopPerikanan.setText("Rp "+df2.format(control.getNjopPerikanan()));
       this.lblNjopPerikananR.setText(df2.format(control.getNjopPerikanan())+"");
        this.lblNjopTotalR.setText(df2.format(control.getTotalNJop())+"");
        
    }
   
  
    
    
    
    
    private void cbTahunPenilaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTahunPenilaianActionPerformed
        // TODO add your handling code here:
        final String tmpNop = txtNop.getText().replace(".", "").replace("-", "");
        final String tahun = this.cbTahunPenilaian.getSelectedItem()+"";     
        control.prosesNjop(tmpNop, tahun);
        
        if(this.cbTahunPenilaian.getSelectedIndex() <= 0)
        {
         inisiasiTableTanah(tmpNop,"");
         inisiasiTableBangunan(tmpNop,"");
        this.inisiasiTablePerikanan(tmpNop, "");
        
        this.btnCetakBangunan.setEnabled(false);
        this.btnCetakIkan.setEnabled(false);
        this.btnCetakTanah.setEnabled(false);
        this.btnCetakRingkasan.setEnabled(false);
        this.nilaiBngBtn.setEnabled(false);
        this.btnCetakNjop.setEnabled(false);
        
        
        
        }else
        {
        this.btnCetakBangunan.setEnabled(true);
        this.btnCetakIkan.setEnabled(true);
        this.btnCetakTanah.setEnabled(true);
        this.btnCetakRingkasan.setEnabled(true);
        this.nilaiBngBtn.setEnabled(true);
        this.btnCetakNjop.setEnabled(true);
        control.buatModel(tmpNop, tahun);
            
        inisiasiTableTanah(tmpNop,tahun);
        inisiasiTableBangunan(tmpNop, tahun);
        this.inisiasiTablePerikanan(tmpNop,tahun);
        }
       
    }//GEN-LAST:event_cbTahunPenilaianActionPerformed

    private void btnCetakIkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakIkanActionPerformed
        // TODO add your handling code here:

        control.cetakReportPendapatan(this.cbTahunPenilaian.getSelectedItem()+"");
    }//GEN-LAST:event_btnCetakIkanActionPerformed

    private void nilaiBngBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiBngBtnActionPerformed
        // TODO add your handling code here:

        final String tmpNop = txtNop.getText().replace(".", "").replace("-", "");
        final String tahun = this.cbTahunPenilaian.getSelectedItem()+"";
        control.penilaianBangunan(tmpNop, tahun);

        this.inisiasiTableBangunan(tmpNop, tahun);
    }//GEN-LAST:event_nilaiBngBtnActionPerformed

    private void btnCetakTanahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakTanahActionPerformed
        // TODO add your handling code here:
        control.cetakReportTanah(this.cbTahunPenilaian.getSelectedItem()+"");

    }//GEN-LAST:event_btnCetakTanahActionPerformed

    private void btnCetakRingkasanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakRingkasanActionPerformed
        // TODO add your handling code here:
        control.cetakReportRingkasan(this.cbTahunPenilaian.getSelectedItem()+"");
    }//GEN-LAST:event_btnCetakRingkasanActionPerformed

    private void btnCetakBangunanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakBangunanActionPerformed
        // TODO add your handling code here:
        control.cetakReportBangunanNilai(this.cbTahunPenilaian.getSelectedItem()+"");
        
    }//GEN-LAST:event_btnCetakBangunanActionPerformed

    private void btnCetakNjopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakNjopActionPerformed
        // TODO add your handling code here:
        control.cetakReportBangunanNjop(this.cbTahunPenilaian.getSelectedItem()+"");
    }//GEN-LAST:event_btnCetakNjopActionPerformed

    
    
    
   

   
 
 
   
   
   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetakBangunan;
    private javax.swing.JButton btnCetakIkan;
    private javax.swing.JButton btnCetakNjop;
    private javax.swing.JButton btnCetakRingkasan;
    private javax.swing.JButton btnCetakTanah;
    private javax.swing.JComboBox cbTahunPenilaian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelKelasBng;
    private javax.swing.JLabel labelLuasTot;
    private javax.swing.JLabel labelNilaiPerM2;
    private javax.swing.JLabel labelNilaiTot;
    private javax.swing.JLabel labelNjopBangunan;
    private javax.swing.JLabel labelNjopPerikanan;
    private javax.swing.JLabel labelNjopTanah;
    private javax.swing.JLabel labelPemilik;
    private javax.swing.JLabel lblNjopBangunanR;
    private javax.swing.JLabel lblNjopPerikananR;
    private javax.swing.JLabel lblNjopTanahR;
    private javax.swing.JLabel lblNjopTotalR;
    private javax.swing.JButton nilaiBngBtn;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JTable tableBangunan;
    private javax.swing.JTable tablePerikanan;
    private javax.swing.JTable tableTanah;
    private javax.swing.JFormattedTextField txtNop;
    // End of variables declaration//GEN-END:variables
}
