/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package id.co.meda.apit.visual.form;

import id.co.meda.apit.enggine.penilaian.PenilaianBangunan;
import id.co.meda.apit.enggine.penilaian.model.LspopNonStandar;
import id.co.meda.apit.enggine.penilaian.model.Spop;
import id.co.meda.apit.visual.controller.ControlProsesPenilaian;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/** 
 *
 * @author PT. Data Bumi Indonesia
 */
public class FrmProsesPenilaian extends javax.swing.JDialog {

    /**
     * Creates new form FrmSpop
     */
    public FrmProsesPenilaian(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inisiasiAwal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEditLspop = new javax.swing.JTable();
        btProses = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbNmWp = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbJmlBng = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbThnPenilaian = new javax.swing.JComboBox();
        txtNop = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Proses Penilaian");
        setResizable(false);

        tblEditLspop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEditLspop.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(tblEditLspop);

        btProses.setMnemonic('P');
        btProses.setText("Proses Penilaian");
        btProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProsesActionPerformed(evt);
            }
        });

        jLabel1.setText("NOP");

        jLabel2.setText("Nama WP");

        lbNmWp.setBackground(new java.awt.Color(255, 255, 255));
        lbNmWp.setForeground(new java.awt.Color(255, 0, 0));
        lbNmWp.setText("-");

        jLabel3.setText("Jumlah Bangunan");

        lbJmlBng.setForeground(new java.awt.Color(255, 0, 0));
        lbJmlBng.setText("-");

        jLabel4.setText("Tahun Penilaian");

        try {
            txtNop.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##.###.###.###-####.#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNopKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btProses, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(lbNmWp, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cbThnPenilaian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lbJmlBng, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNop, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbNmWp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbJmlBng))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btProses)
                    .addComponent(cbThnPenilaian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProsesActionPerformed
        // TODO add your handling code here:
        thnPenilaian = cbThnPenilaian.getSelectedItem().toString();
        
        try {
            if (ctrlProsesPenilaian.cekHslPenilaian(nop, thnPenilaian)) {
                if (JOptionPane.showConfirmDialog(this, "NOP "+nop+" untuk tahun "
                  +thnPenilaian+" sudah pernah dilakukan penilaian, apakah dilakukan penilaian ulang ?", 
                   "Konfirmasi Proses Penilaian", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
                    prosesPenilaian();
                }
            } else {
                prosesPenilaian();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan dengan pesan: "+e.getMessage());
        }
    }//GEN-LAST:event_btProsesActionPerformed
    
    private void prosesPenilaian() {
        btProses.setEnabled(false);
        PenilaianBangunan penilBng = new PenilaianBangunan(nop, thnPenilaian);
        penilBng.mulaiPenilaian();
        JOptionPane.showMessageDialog(this, "Proses penilaian telah selesai dilakukan ...");
        btProses.setEnabled(true);
    }
    
    private void txtNopKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNopKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            nop = txtNop.getText().replace(".","").replace("-","");
            cariNop();
            isiGrid(1);
        }
    }//GEN-LAST:event_txtNopKeyPressed

//            if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
//            nop = txtNop.getText().replace(".","").replace("-","");
//            cariNop();
//            isiGrid(1);
//        }

    

    private void inisiasiAwal() {
        btProses.setEnabled(false);
        ctrlProsesPenilaian.isiCombo(cbThnPenilaian);
        //set selected year-----------------///
        Date date = new Date();
        Calendar cal = Calendar.getInstance();
        cal.setTime(date);
        String year = cal.get(Calendar.YEAR)+"";
        
        cbThnPenilaian.setSelectedItem(year);
        //-----------------------------------///
        
        isiGrid(0);
    }
    
    private void cariNop() {
        spop = new Spop();
        ctrlProsesPenilaian.cariNop(nop,spop);
        
        if (spop.getNop()!=null && ctrlProsesPenilaian.cekBngDiLspop(nop)) {
           lbNmWp.setText(spop.getNamaWp());
           lbJmlBng.setText(spop.getJumlahBangunan().toString());
           btProses.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "NOP tidak ditemukan di data SPOP atau LSPOP !!!");
            btProses.setEnabled(false);
            txtNop.setText("");
            lbNmWp.setText("-");
            lbJmlBng.setText("-");
        }
        
        
    }
    
    private void isiGrid(int kode) {
        if (kode==0) {
            tblEditLspop.setModel(ctrlProsesPenilaian.getTableModel());
        } else {
            tblEditLspop.setModel(ctrlProsesPenilaian.getTableModel(nop));
        }
        tblEditLspop.getColumnModel().getColumn(0).setPreferredWidth(5);        
        tblEditLspop.getColumnModel().getColumn(1).setPreferredWidth(150);        
        tblEditLspop.getColumnModel().getColumn(2).setPreferredWidth(50);        
        tblEditLspop.setRowHeight(35);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btProses;
    private javax.swing.JComboBox cbThnPenilaian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbJmlBng;
    private javax.swing.JLabel lbNmWp;
    private javax.swing.JTable tblEditLspop;
    private javax.swing.JFormattedTextField txtNop;
    // End of variables declaration//GEN-END:variables
    final ControlProsesPenilaian ctrlProsesPenilaian = new ControlProsesPenilaian();
    Spop spop;
    LspopNonStandar lSpop;
    String nop;
    String thnPenilaian;

}
