/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package id.co.meda.apit.visual.form;

import id.co.meda.apit.visual.controller.ControlProsesPenilaianBandara;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author PT. Databumi Indonesia
 */
public class FrmPenilaianBandara extends javax.swing.JDialog {

    private ControlProsesPenilaianBandara control = new ControlProsesPenilaianBandara();
    private String nop = "";
    private String tahun = "";
    
    /**
     * Creates new form FrmPenilaianBandara
     */
    public FrmPenilaianBandara(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        isiTableTanah("","");
        isiTableBngKhusus("","");
        isiTableBngPTDbkb("","");
        isiTableLspop("","");
        control.isiCbTahun(cbTahun);
        cbTahun.setEnabled(false);
        btnProsesPenilBngPTDbkb.setEnabled(false);
        this.btnCetakNilai.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNop = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelNamaBandara = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTanah = new javax.swing.JTable(control.getModelTanah("", "")){
            public Component prepareRenderer(TableCellRenderer render,
                int indexRow, int indexCol)
            {
                Component comp = super.prepareRenderer(render, indexRow, indexCol);
                if(indexCol == 2)
                {
                    comp.setBackground(Color.GREEN);
                }else if(isCellSelected(indexRow,indexCol)){

                    comp.setBackground(Color.YELLOW);
                    comp.setForeground(Color.BLACK);
                }else
                {
                    comp.setBackground(Color.CYAN);
                    comp.setForeground(Color.BLACK);
                }
                return comp;
            }

        };
        jLabel23 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelNjopTanah = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelNjopTanahPerM = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBngKhusus = new javax.swing.JTable(control.getModelBngKhusus("", "")){
            public Component prepareRenderer(TableCellRenderer render,
                int indexRow, int indexCol)
            {
                Component comp = super.prepareRenderer(render, indexRow, indexCol);
                if(indexCol == 2)
                {
                    comp.setBackground(Color.GREEN);
                }else if(isCellSelected(indexRow,indexCol)){

                    comp.setBackground(Color.YELLOW);
                    comp.setForeground(Color.BLACK);
                }else
                {
                    comp.setBackground(Color.CYAN);
                    comp.setForeground(Color.BLACK);
                }
                return comp;
            }

        };
        jLabel24 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelNjopBngKhusus = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelNjopBngKhususPerM = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablePTDBKB = new javax.swing.JTable(control.getModelPTDBKB("", "")){

            public Component prepareRenderer(TableCellRenderer render,
                int indexRow, int indexCol)
            {
                Component comp = super.prepareRenderer(render, indexRow, indexCol);
                if(isCellSelected(indexRow,indexCol)){

                    comp.setBackground(Color.YELLOW);
                    comp.setForeground(Color.BLACK);
                }else
                {
                    comp.setBackground(Color.CYAN);
                    comp.setForeground(Color.BLACK);
                }
                return comp;
            }

        };
        btnProsesPenilBngPTDbkb = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        labelNjopBngPtDBkb = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableLspop = new javax.swing.JTable(control.getModelLspopBandara("","")){

            public Component prepareRenderer(TableCellRenderer render,
                int indexRow, int indexCol)
            {
                Component comp = super.prepareRenderer(render, indexRow, indexCol);
                if(indexCol == 2){
                    comp.setBackground(Color.GREEN);
                }else if(isCellSelected(indexRow,indexCol)){

                    comp.setBackground(Color.YELLOW);
                    comp.setForeground(Color.BLACK);
                }else
                {
                    comp.setBackground(Color.CYAN);
                    comp.setForeground(Color.BLACK);
                }
                return comp;
            }

        };
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        labelNjopLspopBng = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        RnjopTanah = new javax.swing.JLabel();
        RnjopBngKhusus = new javax.swing.JLabel();
        RnjopBngPTDdbkb = new javax.swing.JLabel();
        RnjopBngPT = new javax.swing.JLabel();
        RnjopTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbTahun = new javax.swing.JComboBox();
        btnCetakNilai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Penilaian Bandara");

        try {
            txtNop.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##.###.###.###-####.#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNopActionPerformed(evt);
            }
        });
        txtNop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNopKeyPressed(evt);
            }
        });

        jLabel1.setText("NOP");

        jLabel2.setText("Nama Bandara");

        labelNamaBandara.setText("-");

        tableTanah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableTanah);

        jLabel23.setForeground(new java.awt.Color(0, 51, 255));
        jLabel23.setText("*klik 2 kali pada kolom NIR untuk input nilai NIR");

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setText(":");

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setText("Total NJOP Tanah");

        labelNjopTanah.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        labelNjopTanah.setForeground(new java.awt.Color(0, 153, 0));
        labelNjopTanah.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNjopTanah.setText("Rp. -");

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 0));
        jLabel7.setText(":");

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 0));
        jLabel8.setText("NJOP Tanah Per M2");

        labelNjopTanahPerM.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        labelNjopTanahPerM.setForeground(new java.awt.Color(0, 153, 0));
        labelNjopTanahPerM.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNjopTanahPerM.setText("Rp. -");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelNjopTanahPerM, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelNjopTanah, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(labelNjopTanah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(labelNjopTanahPerM))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Tanah", jPanel3);

        tableBngKhusus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableBngKhusus);

        jLabel24.setForeground(new java.awt.Color(0, 51, 255));
        jLabel24.setText("*klik 2 kali pada kolom Nilai Per M2 untuk input nilai bangunan per M2");

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setText("Total NJOP Bangunan Khusus");

        labelNjopBngKhusus.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        labelNjopBngKhusus.setForeground(new java.awt.Color(0, 153, 0));
        labelNjopBngKhusus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNjopBngKhusus.setText("Rp. -");

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 0));
        jLabel10.setText(":");

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 0));
        jLabel11.setText(":");

        labelNjopBngKhususPerM.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        labelNjopBngKhususPerM.setForeground(new java.awt.Color(0, 153, 0));
        labelNjopBngKhususPerM.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNjopBngKhususPerM.setText("Rp. -");

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 0));
        jLabel12.setText("NJOP Per M2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelNjopBngKhususPerM, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelNjopBngKhusus, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(labelNjopBngKhusus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(labelNjopBngKhususPerM))
                .addGap(12, 12, 12))
        );

        jTabbedPane1.addTab("Bangunan Khusus", jPanel2);

        tablePTDBKB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablePTDBKB);

        btnProsesPenilBngPTDbkb.setText("Proses Penilaian Bangunan");
        btnProsesPenilBngPTDbkb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesPenilBngPTDbkbActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 0));
        jLabel13.setText("Total NJOP Bangunan");

        labelNjopBngPtDBkb.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        labelNjopBngPtDBkb.setForeground(new java.awt.Color(0, 153, 0));
        labelNjopBngPtDBkb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNjopBngPtDBkb.setText("Rp. -");

        jLabel14.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 0));
        jLabel14.setText(":");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelNjopBngPtDBkb, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnProsesPenilBngPTDbkb, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnProsesPenilBngPTDbkb)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(labelNjopBngPtDBkb))
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("Bangunan Pendukung dan Teknis DBKB Non-Standar", jPanel1);

        tableLspop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tableLspop);

        jLabel15.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 0));
        jLabel15.setText(":");

        jLabel16.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 0));
        jLabel16.setText("Total NJOP Bangunan");

        labelNjopLspopBng.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        labelNjopLspopBng.setForeground(new java.awt.Color(0, 153, 0));
        labelNjopLspopBng.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNjopLspopBng.setText("Rp. -");

        jLabel25.setForeground(new java.awt.Color(0, 51, 255));
        jLabel25.setText("*klik 2 kali pada kolom Nilai Per M2 untuk input nilai bangunan per M2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelNjopLspopBng, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(labelNjopLspopBng))
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("Bangunan Pendukung dan Teknis Nilai Per M2", jPanel4);

        jLabel17.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 0));
        jLabel17.setText("NJOP TANAH");

        jLabel18.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 0));
        jLabel18.setText("NJOP BANGUNAN KHUSUS");

        jLabel19.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 0));
        jLabel19.setText("NJOP BANGUNAN PENDUKUNG DAN TEKNIS DBKB NON-STANDAR");

        jLabel20.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 0));
        jLabel20.setText("NJOP BANGUNAN PENDUKUNG DAN TEKNIS NILAI PER M2");

        jLabel21.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 0));
        jLabel21.setText("NJOP BANDARA");

        RnjopTanah.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        RnjopTanah.setForeground(new java.awt.Color(0, 153, 0));
        RnjopTanah.setText("Rp 0.0");

        RnjopBngKhusus.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        RnjopBngKhusus.setForeground(new java.awt.Color(0, 153, 0));
        RnjopBngKhusus.setText("Rp 0.0");

        RnjopBngPTDdbkb.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        RnjopBngPTDdbkb.setForeground(new java.awt.Color(0, 153, 0));
        RnjopBngPTDdbkb.setText("Rp 0.0");

        RnjopBngPT.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        RnjopBngPT.setForeground(new java.awt.Color(0, 153, 0));
        RnjopBngPT.setText("Rp 0.0");

        RnjopTotal.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        RnjopTotal.setForeground(new java.awt.Color(0, 153, 0));
        RnjopTotal.setText("Rp 0.0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RnjopTanah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RnjopBngKhusus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RnjopBngPTDdbkb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RnjopBngPT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RnjopTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(RnjopTanah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(RnjopBngKhusus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(RnjopBngPTDdbkb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(RnjopBngPT))
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(RnjopTotal))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ringkasan", jPanel5);

        jLabel4.setText("Tahun Penilaian");

        cbTahun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTahunActionPerformed(evt);
            }
        });

        btnCetakNilai.setText("Cetak Hasil Penilaian");
        btnCetakNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakNilaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNop, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(labelNamaBandara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCetakNilai)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1)
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelNamaBandara))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cbTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(btnCetakNilai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNopActionPerformed

    private void txtNopKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNopKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            this.nop = txtNop.getText().replace(".", "").replace("-", "");
            
            if (control.cekNOP(nop)) {
                cbTahun.setEnabled(true);
                control.isiCbTahun(cbTahun);
                
                //set selected year-----------------///
                Date date = new Date();
                Calendar cal = Calendar.getInstance();
                cal.setTime(date);
                String year = cal.get(Calendar.YEAR)+"";
                cbTahun.setSelectedItem(year);
                //---------------------------------///
                
                
                this.labelNamaBandara.setText(control.getNamaBandara());
                btnProsesPenilBngPTDbkb.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "NOP tidak ditemukan !!!");
                txtNop.setText("");
                control.isiCbTahun(cbTahun);
                cbTahun.setEnabled(false);
                btnProsesPenilBngPTDbkb.setEnabled(false);
                this.btnCetakNilai.setEnabled(false);
            }
        }
    }//GEN-LAST:event_txtNopKeyPressed

    private void cbTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTahunActionPerformed
        // TODO add your handling code here:
        
        if(cbTahun.getSelectedIndex() > 0)
        {
            tahun = cbTahun.getSelectedItem()+"";
            isiTableTanah(this.nop,this.tahun);
            isiTableBngKhusus(this.nop,this.tahun);
            isiTableBngPTDbkb(this.nop,this.tahun);
            isiTableLspop(this.nop,this.tahun);
            this.btnProsesPenilBngPTDbkb.setEnabled(true);
            this.btnCetakNilai.setEnabled(true);
           this.totalNjop();
        }else
        {
            tahun = cbTahun.getSelectedItem()+"";
            isiTableTanah("","");
            isiTableBngKhusus("","");
            isiTableBngPTDbkb("","");
            isiTableLspop("","");
            this.btnProsesPenilBngPTDbkb.setEnabled(false);
            this.btnCetakNilai.setEnabled(false);
        }
        
        
    }//GEN-LAST:event_cbTahunActionPerformed

    private void btnProsesPenilBngPTDbkbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesPenilBngPTDbkbActionPerformed
        // TODO add your handling code here:
        control.nilaiBngPTDbkb(this.nop,this.tahun);
        this.isiTableBngPTDbkb(nop, tahun);
        totalNjop();
    }//GEN-LAST:event_btnProsesPenilBngPTDbkbActionPerformed

    private void btnCetakNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakNilaiActionPerformed
        // TODO add your handling code here:
        double njopTanah = control.getTotalNjopTanah(nop, tahun);
        double njopBngKhusus = control.getTotalNjopBngKhusus(nop, tahun);
        double njopPTDbkb = control.getTotalNjopBngPTDbkb(nop, tahun);
        double njopPT = control.getTotalNjopLspop(nop, tahun);
        
        double njopTotal = njopTanah + njopBngKhusus + njopPTDbkb + njopPT;
        
        DecimalFormat df = new DecimalFormat( "#,###,###,##0.00" ); 
        control.tampilReport(nop, tahun, 
                "Rp " +df.format(njopTanah), 
                "Rp " +df.format(njopBngKhusus), 
                "Rp " +df.format(njopPTDbkb), 
                "Rp " +df.format(njopPT),
                "Rp " +df.format(njopTotal));
    }//GEN-LAST:event_btnCetakNilaiActionPerformed
    
    private void isiTableTanah(String tempNop, String tempTahun)
    {
        tableTanah.setModel(control.getModelTanah(tempNop, tempTahun));
        tableTanah.getModel().addTableModelListener(new TableModelListener(){
        
            @Override
            public void tableChanged(TableModelEvent e)
            {
                    String jp_tanah = (String)tableTanah.getModel().getValueAt(tableTanah.getSelectedRow(), 0);
                    double luas = (double)tableTanah.getValueAt(tableTanah.getSelectedRow(),1);
                    double nir = (double)tableTanah.getValueAt(tableTanah.getSelectedRow(), 2);
                    
                    control.nilaiTanah(nop, tahun, nir, luas,jp_tanah);
                    
                    //refresh table
                    isiTableTanah(nop,tahun);
                    totalNjop();
            }
        
        });
        
        //isi labelNjopTanah
            DecimalFormat df2 = new DecimalFormat( "#,###,###,##0.00" );
            this.labelNjopTanah.setText("Rp "+df2.format(control.getTotalNjopTanah(nop, tahun)));
            this.labelNjopTanahPerM.setText("Rp "+df2.format(control.getTotalNjopTanahPerM()));
            
     }
    
    private void isiTableBngKhusus(String tempNop, String tempTahun)
    {
        tableBngKhusus.setModel(control.getModelBngKhusus(tempNop, tempTahun));
        tableBngKhusus.getModel().addTableModelListener(new TableModelListener(){
        
            @Override
            public void tableChanged(TableModelEvent e)
            {
                    String jp_tanah = (String)tableBngKhusus.getModel().getValueAt(tableBngKhusus.getSelectedRow(), 0);
                    double luas = (double)tableBngKhusus.getValueAt(tableBngKhusus.getSelectedRow(),1);
                    double nir = (double)tableBngKhusus.getValueAt(tableBngKhusus.getSelectedRow(), 2);
                    
                    control.nilaiBngKhusus(nop, tahun, nir, luas,jp_tanah);
                    
                    //refresh table
                    isiTableBngKhusus(nop,tahun);
                    totalNjop();
            }
        
        });
        
        //isi labelNjopTanah
            DecimalFormat df2 = new DecimalFormat( "#,###,###,##0.00" );
            this.labelNjopBngKhusus.setText("Rp "+df2.format(control.getTotalNjopBngKhusus(nop, tahun)));
            this.labelNjopBngKhususPerM.setText("Rp "+df2.format(control.getTotalNjopBngKhususPerM()));
     }
    
    private void isiTableBngPTDbkb(String tempNop, String tempTahun)
    {
        tablePTDBKB.setModel(control.getModelPTDBKB(tempNop, tempTahun));
        /*
        tableBngKhusus.getModel().addTableModelListener(new TableModelListener(){
        
            @Override
            public void tableChanged(TableModelEvent e)
            {
                    String jp_tanah = (String)tableBngKhusus.getModel().getValueAt(tableBngKhusus.getSelectedRow(), 0);
                    double luas = (double)tableBngKhusus.getValueAt(tableBngKhusus.getSelectedRow(),1);
                    double nir = (double)tableBngKhusus.getValueAt(tableBngKhusus.getSelectedRow(), 2);
                    
                    control.nilaiBngKhusus(nop, tahun, nir, luas,jp_tanah);
                    
                    //refresh table
                    isiTableBngKhusus(nop,tahun);
            }
        
        });
        
        //isi labelNjopTanah
            DecimalFormat df2 = new DecimalFormat( "#,###,###,##0.00" );
            this.labelNjopBngKhusus.setText("Rp "+df2.format(control.getTotalNjopBngKhusus(nop, tahun)));
            this.labelNjopBngKhususPerM.setText("Rp "+df2.format(control.getTotalNjopBngKhususPerM()));
        */
        if(!tempNop.equalsIgnoreCase("") && !tempTahun.equalsIgnoreCase(""))
        {
            DecimalFormat df2 = new DecimalFormat( "#,###,###,##0.00" );
            this.labelNjopBngPtDBkb.setText("Rp "+df2.format(control.getTotalNjopBngPTDbkb(nop, tahun)));
        }else
        {
            this.labelNjopBngPtDBkb.setText("Rp 0.0");
        
        }
    }
    
    
    private void isiTableLspop(String nop, String tahun)
    {   
        this.tableLspop.setModel(control.getModelLspopBandara(nop, tahun));
        this.tableLspop.removeColumn(this.tableLspop.getColumnModel().getColumn(0));
        
        final String nop1 = nop;
        final String tahun1 = tahun;
        
        this.tableLspop.getModel().addTableModelListener(new TableModelListener(){
        
            @Override
            public void tableChanged(TableModelEvent e)
            {
                double luas = (double)tableLspop.getModel().getValueAt(tableLspop.getSelectedRow(), 2);
                double nilPerM = (double)tableLspop.getModel().getValueAt(tableLspop.getSelectedRow(), 3);
                int noBng = Integer.parseInt((String) 
                        tableLspop.getModel().getValueAt(tableLspop.getSelectedRow(), 0));
                control.nilaiLspopBandara(nop1, tahun1, noBng, nilPerM, luas);
                
                isiTableLspop(nop1,tahun1);
                totalNjop();
            }
        
        });
        
        if(!nop.equalsIgnoreCase("") && !tahun.equalsIgnoreCase(""))
        {
            DecimalFormat df2 = new DecimalFormat( "#,###,###,##0.00" );
            this.labelNjopLspopBng.setText("Rp "+df2.format(control.getTotalNjopLspop(nop, tahun)));
        }else
        {
            this.labelNjopLspopBng.setText("Rp 0.0");
        
        }
    }
    
    public void totalNjop()
    {
        double njopTanah = control.getTotalNjopTanah(nop, tahun);
        double njopBngKhusus = control.getTotalNjopBngKhusus(nop, tahun);
        double njopPTDbkb = control.getTotalNjopBngPTDbkb(nop, tahun);
        double njopPT = control.getTotalNjopLspop(nop, tahun);
        
        double njopTotal = njopTanah + njopBngKhusus + njopPTDbkb + njopPT;
        
        DecimalFormat df = new DecimalFormat( "#,###,###,##0.00" );
        this.RnjopTanah.setText("Rp "+df.format(njopTanah));
        this.RnjopBngKhusus.setText("Rp "+df.format(njopBngKhusus));
        this.RnjopBngPTDdbkb.setText("Rp "+df.format(njopPTDbkb));
        this.RnjopBngPT.setText("Rp "+df.format(njopPT));
        this.RnjopTotal.setText("Rp "+df.format(njopTotal));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RnjopBngKhusus;
    private javax.swing.JLabel RnjopBngPT;
    private javax.swing.JLabel RnjopBngPTDdbkb;
    private javax.swing.JLabel RnjopTanah;
    private javax.swing.JLabel RnjopTotal;
    private javax.swing.JButton btnCetakNilai;
    private javax.swing.JButton btnProsesPenilBngPTDbkb;
    private javax.swing.JComboBox cbTahun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelNamaBandara;
    private javax.swing.JLabel labelNjopBngKhusus;
    private javax.swing.JLabel labelNjopBngKhususPerM;
    private javax.swing.JLabel labelNjopBngPtDBkb;
    private javax.swing.JLabel labelNjopLspopBng;
    private javax.swing.JLabel labelNjopTanah;
    private javax.swing.JLabel labelNjopTanahPerM;
    private javax.swing.JTable tableBngKhusus;
    private javax.swing.JTable tableLspop;
    private javax.swing.JTable tablePTDBKB;
    private javax.swing.JTable tableTanah;
    private javax.swing.JFormattedTextField txtNop;
    // End of variables declaration//GEN-END:variables
}
