/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package id.co.meda.apit.visual.form;

import id.co.meda.apit.visual.controller.ControlSalinDbkb;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.Document;

/**
 *
 * @author PT. Databumi Indonesia
 */
public class FrmSalinDbkb extends javax.swing.JDialog {
    ControlSalinDbkb salin = new ControlSalinDbkb();
    /**
     * Creates new form FrmSalinDbkb
     */
    public FrmSalinDbkb(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.btnProsesSalin.setEnabled(false);
        this.cmbDariTahun = salin.getComboBoxItem(cmbDariTahun);
        
        this.textFieldTahunTujuan.setEnabled(false);
        Document Pagardoc = this.textFieldTahunTujuan.getDocument();
        Pagardoc.addDocumentListener(new stateDoc(this.btnProsesSalin));
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        cmbDariTahun = new javax.swing.JComboBox();
        label2 = new java.awt.Label();
        textFieldTahunTujuan = new javax.swing.JTextField();
        btnProsesSalin = new javax.swing.JButton();
        labelSalinProses = new java.awt.Label();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Salin DBKB");

        label1.setText("Dari Tahun");

        cmbDariTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDariTahunActionPerformed(evt);
            }
        });

        label2.setText("Ke Tahun");

        btnProsesSalin.setText("Proses");
        btnProsesSalin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesSalinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbDariTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldTahunTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnProsesSalin, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelSalinProses, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textFieldTahunTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnProsesSalin))
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmbDariTahun, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSalinProses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(549, 163));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbDariTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDariTahunActionPerformed
        // TODO add your handling code here:
        if(cmbDariTahun.getSelectedIndex() != 0)
        {
            Calendar calendar = Calendar.getInstance();
            int year = calendar.get(Calendar.YEAR);
            this.textFieldTahunTujuan.setEnabled(true);
            this.textFieldTahunTujuan.setText(""+year);
        }else
        {
             this.textFieldTahunTujuan.setEnabled(false);
             this.textFieldTahunTujuan.setText(null);
             
        }
    }//GEN-LAST:event_cmbDariTahunActionPerformed

    private void btnProsesSalinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesSalinActionPerformed
        // TODO add your handling code here:
        
        if(salin.cekSalinTujuan(this.textFieldTahunTujuan.getText(),this.labelSalinProses,this.jProgressBar1))
        {
            Task task = new Task();
            task.execute();
            
        }else
        {
            this.jProgressBar1.setValue(0);
            JOptionPane.showMessageDialog(rootPane, "Data sudah pernah disalin ke tahun tujuan", 
                    "Info Salin Data", JOptionPane.INFORMATION_MESSAGE);
            this.textFieldTahunTujuan.setText("");
            this.cmbDariTahun.setSelectedIndex(0);
        }    
           
    }//GEN-LAST:event_btnProsesSalinActionPerformed
    
    public void disableAll()
    {
        this.btnProsesSalin.setEnabled(false);
        this.cmbDariTahun.setEnabled(false);
        this.textFieldTahunTujuan.setEnabled(false);
    }
    
    public void enableAll()
    {
        this.btnProsesSalin.setEnabled(true);
        this.cmbDariTahun.setEnabled(true);
        this.textFieldTahunTujuan.setEnabled(true);
    }
    
    
     class Task extends SwingWorker<Void, Void> {

        @Override
        protected Void doInBackground(){
            
            disableAll();
           
            jProgressBar1.setMinimum(0);
            jProgressBar1.setMaximum(100);
            jProgressBar1.setStringPainted(true);
            
            salin.prosesSalin(cmbDariTahun.getSelectedItem()+"",
                    textFieldTahunTujuan.getText(),labelSalinProses,jProgressBar1);
            return null;
        }
        @Override
        protected void done()
        {
            enableAll();
           jProgressBar1.setValue(0);
           jProgressBar1.setString("");
           JOptionPane.showMessageDialog(rootPane, "Data telah berhasil di salin", "informasi salin data", JOptionPane.INFORMATION_MESSAGE);
           cmbDariTahun.addItem(textFieldTahunTujuan.getText()+"");
           labelSalinProses.setText("");
        }
     }
 
    
    
    
    
    class stateDoc implements DocumentListener{
    
        private JButton btnField;
    
        public stateDoc(JButton btnField)
        {
            this.btnField = btnField;
        }
       
        public void setEnabledDisable(DocumentEvent e)
        {
            if (e.getDocument().getLength() > 0){
                this.btnField.setEnabled(true);
            }else
            {
                this.btnField.setEnabled(false);
            }
        }
        
        @Override
        public void insertUpdate(DocumentEvent e) {
            setEnabledDisable(e);
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            setEnabledDisable(e);
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            setEnabledDisable(e);
        }
    
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProsesSalin;
    private javax.swing.JComboBox cmbDariTahun;
    private javax.swing.JProgressBar jProgressBar1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label labelSalinProses;
    private javax.swing.JTextField textFieldTahunTujuan;
    // End of variables declaration//GEN-END:variables
}
