/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package id.co.meda.apit.visual.form;

import id.co.meda.apit.enggine.penilaian.khusus.pelabuhan.SpopPelabuhan;
import id.co.meda.apit.visual.controller.ControlSpopPelabuhan;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author PT. Databumi Indonesia
 */
public class FrmSpopPelabuhan extends javax.swing.JDialog {
    
    private ControlSpopPelabuhan control = new ControlSpopPelabuhan();
    
    /**
     * Creates new form FrmCrnPelabuhan
     */
    public FrmSpopPelabuhan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.cbJnsPelabuhan.setEnabled(false);
        this.enableAll(false);
    }
    
    public FrmSpopPelabuhan(java.awt.Frame parent, boolean modal, String nop) {
        super(parent, modal);
        initComponents();
        editMode(nop);
    }
    
    private void editMode(String nop)
    {
        SpopPelabuhan spop = control.getSpopPelabuhan(nop);
                    cbJnsPelabuhan.setEnabled(true);
                    cbJnsPelabuhan.setSelectedItem(spop.getJenisPelabuhan());
                    namaPelabuhanField.setText(spop.getNamaPelabuhan());
                    alamatPelabuhanField.setText(spop.getAlamatPelabuhan());
                    enableAll(true);
                    txtNop.setEnabled(false);
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNop = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namaPelabuhanField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        alamatPelabuhanField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbJnsPelabuhan = new javax.swing.JComboBox();
        btnSimpanField = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        try {
            txtNop.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##.###.###.###-####.#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNopActionPerformed(evt);
            }
        });
        txtNop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNopKeyPressed(evt);
            }
        });

        jLabel1.setText("NOP");

        jLabel3.setText("Nama Pelabuhan");

        jLabel4.setText("Alamat Pelabuhan");

        jLabel5.setText("Jenis Pelabuhan");

        cbJnsPelabuhan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Jenis Pelabuhan", "BREASTING/MORRING DOLPHIN", "JETTY/DERMAGA", "CONNECTION BRIDGE" }));
        cbJnsPelabuhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJnsPelabuhanActionPerformed(evt);
            }
        });

        btnSimpanField.setText("Simpan");
        btnSimpanField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSimpanField))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNop, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaPelabuhanField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alamatPelabuhanField)
                            .addComponent(cbJnsPelabuhan, 0, 236, Short.MAX_VALUE))))
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbJnsPelabuhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaPelabuhanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alamatPelabuhanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25)
                .addComponent(btnSimpanField)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNopActionPerformed

    private void txtNopKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNopKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String tmpNop = txtNop.getText().replace(".", "").replace("-", "");
            if(tmpNop.equalsIgnoreCase(""))
            {
                    cbJnsPelabuhan.setEnabled(false);
                    this.namaPelabuhanField.setText("");
                    this.alamatPelabuhanField.setText("");
                    enableAll(false);
                
                
            }else
            {
                if (control.cekNOP(tmpNop)) {
                    
                    SpopPelabuhan spop = control.getSpopPelabuhan(tmpNop);
                    cbJnsPelabuhan.setEnabled(true);
                    cbJnsPelabuhan.setSelectedItem(spop.getJenisPelabuhan());
                    namaPelabuhanField.setText(spop.getNamaPelabuhan());
                    alamatPelabuhanField.setText(spop.getAlamatPelabuhan());
                    enableAll(true);
                    txtNop.setEnabled(false);
                }else
                {
                    cbJnsPelabuhan.setEnabled(true);
                    enableAll(false);
                }
            }
        }
    }//GEN-LAST:event_txtNopKeyPressed

    private void cbJnsPelabuhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJnsPelabuhanActionPerformed
        // TODO add your handling code here:
        if(this.cbJnsPelabuhan.getSelectedIndex() > 0)
        {
            enableAll(true);
        }else
        {
            enableAll(false);
        }
    }//GEN-LAST:event_cbJnsPelabuhanActionPerformed

    private void btnSimpanFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanFieldActionPerformed
        // TODO add your handling code here:
        
        SpopPelabuhan spop = new SpopPelabuhan();
        spop.setNop( txtNop.getText().replace(".", "").replace("-", ""));
        spop.setNamaPelabuhan(this.namaPelabuhanField.getText());
        spop.setJenisPelabuhan(cbJnsPelabuhan.getSelectedItem()+"");
        spop.setAlamatPelabuhan(this.alamatPelabuhanField.getText());
        
        if(control.simpan(spop))
        {
            JOptionPane.showMessageDialog(rootPane, 
                    "Data berhasil disimpan", "Penyimpanan Spop", JOptionPane.INFORMATION_MESSAGE);
        }else
        {
            JOptionPane.showMessageDialog(rootPane, 
                    "Data gagal disimpan", "Penyimpanan Spop", JOptionPane.ERROR_MESSAGE); 
        }
        
    }//GEN-LAST:event_btnSimpanFieldActionPerformed

    private void enableAll(boolean temp)
    {
        this.alamatPelabuhanField.setEnabled(temp);
        this.namaPelabuhanField.setEnabled(temp);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatPelabuhanField;
    private javax.swing.JButton btnSimpanField;
    private javax.swing.JComboBox cbJnsPelabuhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField namaPelabuhanField;
    private javax.swing.JFormattedTextField txtNop;
    // End of variables declaration//GEN-END:variables
}
