/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package id.co.meda.apit.visual.form;

import id.co.meda.apit.visual.controller.ControlPengguna;
import id.co.meda.apit.visual.controller.Pengguna;
import id.co.meda.apit.visual.controller.SecEncryptDecrypt;
import javax.swing.JOptionPane;

/**
 *
 * @author PT. Data Bumi Indonesia
 */
public class FrmUbahProfil extends javax.swing.JDialog {

    /**
     * Creates new form FrmUbahProfil
     */
    public FrmUbahProfil(java.awt.Frame parent, boolean modal,Pengguna pengguna) {
        super(parent, modal);
        initComponents();
        this.pengguna = pengguna;
        isiData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNip = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNmLkp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lbWenang = new javax.swing.JLabel();
        cbUbahPwd = new javax.swing.JCheckBox();
        txtPwdSaatIni = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPwdBaru = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        txtPwdKonf = new javax.swing.JPasswordField();
        btSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Profil Pengguna");

        jLabel2.setText("User");

        jLabel3.setText("NIP");

        jLabel4.setText("Nama Lengkap");

        txtNmLkp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNmLkpActionPerformed(evt);
            }
        });

        jLabel5.setText("Kewenangan");

        lbWenang.setText("Kewenangan");

        cbUbahPwd.setText("Ubah Password");
        cbUbahPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUbahPwdActionPerformed(evt);
            }
        });

        txtPwdSaatIni.setEnabled(false);

        jLabel7.setText("Pwd Saat Ini");

        jLabel8.setText("Pwd Baru");

        txtPwdBaru.setEnabled(false);

        jLabel9.setText("Konfirmasi");

        txtPwdKonf.setEnabled(false);

        btSimpan.setText("Simpan");
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNip, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNmLkp, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbWenang, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUbahPwd)
                            .addComponent(txtPwdSaatIni, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPwdKonf, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPwdBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSimpan))
                        .addGap(51, 51, 51)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNmLkp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbWenang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbUbahPwd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPwdSaatIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPwdBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPwdKonf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSimpan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void isiData() {
        txtUser.setText(pengguna.getNmUser());
        txtNip.setText(pengguna.getNip());
        txtNmLkp.setText(pengguna.getNmLengkap());
        lbWenang.setText(ctrlPeng.ambilNmRole(pengguna.getKdRole()));
    }
    
    private void cbUbahPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUbahPwdActionPerformed
        // TODO add your handling code here:
       txtPwdSaatIni.setEnabled(cbUbahPwd.isSelected());
       txtPwdBaru.setEnabled(cbUbahPwd.isSelected());
       txtPwdKonf.setEnabled(cbUbahPwd.isSelected());
    }//GEN-LAST:event_cbUbahPwdActionPerformed

    private void txtNmLkpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNmLkpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNmLkpActionPerformed

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
        // TODO add your handling code here:
        boolean kdLanjut = true;
        if (cbUbahPwd.isSelected()) {
            if (pengguna.getPwd().equals(SecEncryptDecrypt.EncryptText(new String(txtPwdSaatIni.getPassword())))) {
                if ((new String(txtPwdBaru.getPassword()).equals(new String(txtPwdKonf.getPassword()))) &&
                    new String(txtPwdBaru.getPassword()).length()>0){
                    kdLanjut = true;
                } else {
                    JOptionPane.showMessageDialog(this, "Password baru anda berbeda dengan konfirmasi, silahkan ulangi kembali ...");
                    kdLanjut = false;
                    txtPwdBaru.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Password anda saat ini salah, anda tidak dapat mengubah password..");
                kdLanjut = false;
                txtPwdSaatIni.requestFocus();
            }
        }
        
        if (kdLanjut) {
            pengguna.setNip((txtNip.getText().length()>0)?txtNip.getText():"-");
            pengguna.setNmLengkap((txtNmLkp.getText().length()>0)?txtNmLkp.getText():"-");
            pengguna.setNmUser((txtUser.getText().length()>0)?txtUser.getText():"-");
            if (cbUbahPwd.isSelected()) {
                pengguna.setPwd(SecEncryptDecrypt.EncryptText(new String(txtPwdBaru.getPassword())));
            }
            String hasil = ctrlPeng.updatePengguna(pengguna);
            if (hasil.equals("ok")) {
                JOptionPane.showMessageDialog(this, "Perubahan berhasil disimpan ...");
            } else {
                JOptionPane.showMessageDialog(this, hasil);
            }
            this.setVisible(false);
        }

    }//GEN-LAST:event_btSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSimpan;
    private javax.swing.JCheckBox cbUbahPwd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbWenang;
    private javax.swing.JTextField txtNip;
    private javax.swing.JTextField txtNmLkp;
    private javax.swing.JPasswordField txtPwdBaru;
    private javax.swing.JPasswordField txtPwdKonf;
    private javax.swing.JPasswordField txtPwdSaatIni;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
    
    private Pengguna pengguna = new Pengguna();
    private final ControlPengguna ctrlPeng = new ControlPengguna();
}
