/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package id.co.meda.apit.visual.form;

import id.co.meda.apit.database.connection.DBConnectionOracle;
import id.co.meda.apit.database.connection.Konfigurasi;
import id.co.meda.apit.database.connection.ToolsKonfigurasi;
import id.co.meda.apit.visual.controller.Pengguna;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.net.URL;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author PT. Databumi Indonesia
 */
public class FrmUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     * @param pengguna
     */
    public FrmUtama(Pengguna pengguna) {
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);
        this.setIconImage(new ImageIcon(getClass()
                    .getResource("/id/co/meda/apit/visual/resource/home_white.png")).getImage());
        this.pengguna = pengguna;
        lbDispUser.setText(pengguna.getNip() + " - " + pengguna.getNmLengkap());
        setTitle("SIPP");
        aturMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        lbDispUser = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        mUbahProfil = new javax.swing.JMenuItem();
        mTambahPengguna = new javax.swing.JMenuItem();
        kelolaPejabat = new javax.swing.JMenuItem();
        mKeluar = new javax.swing.JMenuItem();
        mDbkb = new javax.swing.JMenu();
        mSalinDbkb = new javax.swing.JMenuItem();
        mEditRef = new javax.swing.JMenu();
        mDhkm = new javax.swing.JMenuItem();
        mDhkf = new javax.swing.JMenuItem();
        mHitDbkb = new javax.swing.JMenuItem();
        mLihatDbkb = new javax.swing.JMenu();
        mKompUt = new javax.swing.JMenuItem();
        mKompMat = new javax.swing.JMenuItem();
        mKomFas = new javax.swing.JMenuItem();
        mPenilUmum = new javax.swing.JMenu();
        mHubSismiop = new javax.swing.JMenu();
        mImpSismiop = new javax.swing.JMenuItem();
        mEditData = new javax.swing.JMenu();
        mSpop = new javax.swing.JMenuItem();
        mLspop = new javax.swing.JMenuItem();
        mProsesPenilaian = new javax.swing.JMenuItem();
        mLihatHasilPenilaian = new javax.swing.JMenuItem();
        mPenilKhusus = new javax.swing.JMenu();
        mTower = new javax.swing.JMenu();
        mTowerDHKM = new javax.swing.JMenuItem();
        mTowerInputData = new javax.swing.JMenu();
        mTowerSpop = new javax.swing.JMenuItem();
        mToweLspop = new javax.swing.JMenuItem();
        mTowerPenilaian = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        lkokTanah = new javax.swing.JMenuItem();
        lkokBngUmum = new javax.swing.JMenuItem();
        lspopKhusus = new javax.swing.JMenuItem();
        lspopBandaraNonDbkb = new javax.swing.JMenuItem();
        prosesPenilaianBandara = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        spopPelabuhan = new javax.swing.JMenuItem();
        hitungCrnPelabuhan = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem11.setText("jMenuItem11");

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenu1.setText("jMenu1");

        jMenuItem2.setText("jMenuItem2");

        jMenu4.setText("jMenu4");

        jMenu8.setText("jMenu8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Penilaian Properti");
        setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/meda/apit/visual/resource/building_2.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(0, 0));
        jLabel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel2.setPreferredSize(new java.awt.Dimension(0, 0));

        lbDispUser.setBackground(new java.awt.Color(0, 0, 0));
        lbDispUser.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbDispUser.setForeground(new java.awt.Color(255, 255, 255));
        lbDispUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbDispUser.setOpaque(true);
        lbDispUser.setPreferredSize(new java.awt.Dimension(34, 15));

        mFile.setMnemonic('f');
        mFile.setText("File");

        mUbahProfil.setText("Ubah Profil Pengguna");
        mUbahProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mUbahProfilActionPerformed(evt);
            }
        });
        mFile.add(mUbahProfil);

        mTambahPengguna.setText("Tambah Pengguna");
        mTambahPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTambahPenggunaActionPerformed(evt);
            }
        });
        mFile.add(mTambahPengguna);

        kelolaPejabat.setText("Kelola Report");
        kelolaPejabat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelolaPejabatActionPerformed(evt);
            }
        });
        mFile.add(kelolaPejabat);

        mKeluar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mKeluar.setText("Keluar");
        mKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mKeluarActionPerformed(evt);
            }
        });
        mFile.add(mKeluar);

        jMenuBar2.add(mFile);

        mDbkb.setMnemonic('H');
        mDbkb.setText("Hitungan DBKB");

        mSalinDbkb.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mSalinDbkb.setText("Salin DBKB dari Tahun Sebelumnya");
        mSalinDbkb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalinDbkbActionPerformed(evt);
            }
        });
        mDbkb.add(mSalinDbkb);

        mEditRef.setText("Edit Referensi");

        mDhkm.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mDhkm.setText("Daftar Harga Komponen Material");
        mDhkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDhkmActionPerformed(evt);
            }
        });
        mEditRef.add(mDhkm);

        mDhkf.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mDhkf.setText("Daftar Harga Komponen Fasilitas");
        mDhkf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDhkfActionPerformed(evt);
            }
        });
        mEditRef.add(mDhkf);

        mDbkb.add(mEditRef);

        mHitDbkb.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mHitDbkb.setText("Hitung DBKB");
        mHitDbkb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mHitDbkbActionPerformed(evt);
            }
        });
        mDbkb.add(mHitDbkb);

        mLihatDbkb.setText("Lihat DBKB");

        mKompUt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mKompUt.setText("Komponen Utama");
        mKompUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mKompUtActionPerformed(evt);
            }
        });
        mLihatDbkb.add(mKompUt);

        mKompMat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mKompMat.setText("Komponen Material");
        mKompMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mKompMatActionPerformed(evt);
            }
        });
        mLihatDbkb.add(mKompMat);

        mKomFas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mKomFas.setText("Komponen Fasilitas");
        mKomFas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mKomFasActionPerformed(evt);
            }
        });
        mLihatDbkb.add(mKomFas);

        mDbkb.add(mLihatDbkb);

        jMenuBar2.add(mDbkb);

        mPenilUmum.setMnemonic('U');
        mPenilUmum.setText("Penilaian OP Umum");

        mHubSismiop.setText("Hubungan dengan SISMIOP");

        mImpSismiop.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mImpSismiop.setText("Import Data dari SISMIOP");
        mImpSismiop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mImpSismiopActionPerformed(evt);
            }
        });
        mHubSismiop.add(mImpSismiop);

        mPenilUmum.add(mHubSismiop);

        mEditData.setText("Edit Data");

        mSpop.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mSpop.setText("SPOP");
        mSpop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSpopActionPerformed(evt);
            }
        });
        mEditData.add(mSpop);

        mLspop.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mLspop.setText("LSPOP");
        mLspop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLspopActionPerformed(evt);
            }
        });
        mEditData.add(mLspop);

        mPenilUmum.add(mEditData);

        mProsesPenilaian.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mProsesPenilaian.setText("Proses Penilaian");
        mProsesPenilaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mProsesPenilaianActionPerformed(evt);
            }
        });
        mPenilUmum.add(mProsesPenilaian);

        mLihatHasilPenilaian.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mLihatHasilPenilaian.setText("Lihat Hasil Penilaian");
        mLihatHasilPenilaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLihatHasilPenilaianActionPerformed(evt);
            }
        });
        mPenilUmum.add(mLihatHasilPenilaian);

        jMenuBar2.add(mPenilUmum);

        mPenilKhusus.setMnemonic('K');
        mPenilKhusus.setText("Penilaian OP Khusus");

        mTower.setText("Penilaian Tower");

        mTowerDHKM.setText("Daftar Harga Komponen Material");
        mTowerDHKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTowerDHKMActionPerformed(evt);
            }
        });
        mTower.add(mTowerDHKM);

        mTowerInputData.setText("Input Data");

        mTowerSpop.setText("SPOP");
        mTowerSpop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTowerSpopActionPerformed(evt);
            }
        });
        mTowerInputData.add(mTowerSpop);

        mToweLspop.setText("LSPOP");
        mToweLspop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mToweLspopActionPerformed(evt);
            }
        });
        mTowerInputData.add(mToweLspop);

        mTower.add(mTowerInputData);

        mTowerPenilaian.setText("Proses Penilaian");
        mTowerPenilaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTowerPenilaianActionPerformed(evt);
            }
        });
        mTower.add(mTowerPenilaian);

        mPenilKhusus.add(mTower);

        jMenu7.setText("Penilaian Bandara");

        jMenu9.setText("Input Data");

        lkokTanah.setText("LKOK Tanah");
        lkokTanah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lkokTanahActionPerformed(evt);
            }
        });
        jMenu9.add(lkokTanah);

        lkokBngUmum.setText("LKOK Bangunan Khusus");
        lkokBngUmum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lkokBngUmumActionPerformed(evt);
            }
        });
        jMenu9.add(lkokBngUmum);

        lspopKhusus.setText("LSPOP Bangunan Pendukung dan Teknis ");
        lspopKhusus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lspopKhususActionPerformed(evt);
            }
        });
        jMenu9.add(lspopKhusus);

        lspopBandaraNonDbkb.setText("LSPOP Bangunan Pendukung dan Teknis  Non DBKB");
        lspopBandaraNonDbkb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lspopBandaraNonDbkbActionPerformed(evt);
            }
        });
        jMenu9.add(lspopBandaraNonDbkb);

        jMenu7.add(jMenu9);

        prosesPenilaianBandara.setText("Proses Penilaian");
        prosesPenilaianBandara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesPenilaianBandaraActionPerformed(evt);
            }
        });
        jMenu7.add(prosesPenilaianBandara);

        mPenilKhusus.add(jMenu7);

        jMenu10.setText("Penilaian Pelabuhan");

        spopPelabuhan.setText("SPOP Pelabuhan");
        spopPelabuhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spopPelabuhanActionPerformed(evt);
            }
        });
        jMenu10.add(spopPelabuhan);

        hitungCrnPelabuhan.setText("Hitung CRN");
        hitungCrnPelabuhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungCrnPelabuhanActionPerformed(evt);
            }
        });
        jMenu10.add(hitungCrnPelabuhan);

        mPenilKhusus.add(jMenu10);

        jMenuBar2.add(mPenilKhusus);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbDispUser, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbDispUser, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1027, 705));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void aturMenu() {
        switch (pengguna.getKdRole()) {
            case "02" :
                mTambahPengguna.setEnabled(false);
                mHubSismiop.setEnabled(false);
                mEditData.setEnabled(false);
                mProsesPenilaian.setEnabled(false);
                break;
            case "03" :
                mTambahPengguna.setEnabled(false);
                mSalinDbkb.setEnabled(false);
                mEditRef.setEnabled(false);
                mHitDbkb.setEnabled(false);
                break;
            case "04" :
                mTambahPengguna.setEnabled(false);
                mHubSismiop.setEnabled(false);
                mSalinDbkb.setEnabled(false);
                mEditRef.setEnabled(false);
                mHitDbkb.setEnabled(false);
                mEditData.setEnabled(false);
                mProsesPenilaian.setEnabled(false);
                break;
        }
    }
    
    private void mSalinDbkbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalinDbkbActionPerformed
        // TODO add your handling code here:
        FrmSalinDbkb salinDbkb = new FrmSalinDbkb(this,true);
        salinDbkb.setVisible(true);
    }//GEN-LAST:event_mSalinDbkbActionPerformed

    private void mLspopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLspopActionPerformed
        // TODO add your handling code here:
        FrmEditLspopNonStd editLspop = new FrmEditLspopNonStd(this, true);
        editLspop.setVisible(true);
        
    }//GEN-LAST:event_mLspopActionPerformed

    private void mDhkmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDhkmActionPerformed
        // TODO add your handling code here:
        FrmDhkmf dhkmf = new FrmDhkmf(this,true,"M");
        dhkmf.setTitle("Daftar Harga Komponen Material");
        dhkmf.setVisible(true);
    }//GEN-LAST:event_mDhkmActionPerformed

    private void mDhkfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDhkfActionPerformed
        // TODO add your handling code here:
        FrmDhkmf dhkmf = new FrmDhkmf(this,true,"F");
        dhkmf.setTitle("Daftar Harga Komponen Fasilitas");
        dhkmf.setVisible(true);   
    }//GEN-LAST:event_mDhkfActionPerformed

    private void mHitDbkbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mHitDbkbActionPerformed
        // TODO add your handling code here:
        FrmHitungDbkb hitung = new FrmHitungDbkb(this,true);
        hitung.setVisible(true);
    }//GEN-LAST:event_mHitDbkbActionPerformed

    private void mKompUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mKompUtActionPerformed
        // TODO add your handling code here:
        FrmLihatKu lihatKu = new FrmLihatKu(this,true);
        lihatKu.setVisible(true);
    }//GEN-LAST:event_mKompUtActionPerformed

    private void mKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_mKeluarActionPerformed

    private void mKompMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mKompMatActionPerformed
        // TODO add your handling code here:
        FrmLihatMaterial material = new FrmLihatMaterial(this,true);
        material.setVisible(true);
    }//GEN-LAST:event_mKompMatActionPerformed

    private void mKomFasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mKomFasActionPerformed
        // TODO add your handling code here:
        Fasilitas fasilitasDBKB = new Fasilitas(this,true);
        fasilitasDBKB.Start();
        fasilitasDBKB.setVisible(true);    
    }//GEN-LAST:event_mKomFasActionPerformed

    private void mSpopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSpopActionPerformed
        // TODO add your handling code here:
        FrmEditSpop editSpop = new FrmEditSpop(this, true);
        editSpop.setVisible(true);
    }//GEN-LAST:event_mSpopActionPerformed

    private void mProsesPenilaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mProsesPenilaianActionPerformed
        // TODO add your handling code here:
        FrmProsesPenilaian prosesPenil = new FrmProsesPenilaian(this, true);
        prosesPenil.setVisible(true);
    }//GEN-LAST:event_mProsesPenilaianActionPerformed

    private void mLihatHasilPenilaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLihatHasilPenilaianActionPerformed
        // TODO add your handling code here:
        FrmLihatPenilaian lihatPenilaian = new FrmLihatPenilaian(this, true);
        lihatPenilaian.setVisible(true);
    }//GEN-LAST:event_mLihatHasilPenilaianActionPerformed

    private void mUbahProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mUbahProfilActionPerformed
        // TODO add your handling code here:
        FrmUbahProfil frmUbah = new FrmUbahProfil(this, true, pengguna);
        frmUbah.setVisible(true);
    }//GEN-LAST:event_mUbahProfilActionPerformed

    private void mTambahPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTambahPenggunaActionPerformed
        // TODO add your handling code here:
        FrmEditPengguna frmPengguna = new FrmEditPengguna(this, true);
        frmPengguna.setVisible(true);
    }//GEN-LAST:event_mTambahPenggunaActionPerformed

    private void mImpSismiopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mImpSismiopActionPerformed
        // TODO add your handling code here:
        if (ToolsKonfigurasi.cekFileKonf()) {
            try {
                Konfigurasi konf = ToolsKonfigurasi.bacaKonf();
                DBConnectionOracle db = new DBConnectionOracle(konf.getDbSisConnStr(), konf.getDbSisUser(), konf.getDbSisPwd());
                Connection conn = db.getConnect();
                if (conn==null) {
                    JOptionPane.showMessageDialog(this, "Koneksi ke server SISMIOP gagal, cek kembali konfigurasi anda..");
                } else {
                    FrmImportSismiop frmSis = new FrmImportSismiop(this, true, conn);
                    frmSis.setVisible(true);
                }
            } catch (Exception e) {}
        } else {
            JOptionPane.showMessageDialog(this, "Koneksi ke server SISMIOP tidak dapat dilakukan,"
                    + "\nperlu dilakukan setting file konfigurasi. "
                    + "\nHubungi administrator aplikasi ...");
        }
    }//GEN-LAST:event_mImpSismiopActionPerformed

    private void mTowerDHKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTowerDHKMActionPerformed
        // TODO add your handling code here:
        FrmTowerDhkm frmDhkm = new FrmTowerDhkm(this, true);
        frmDhkm.setVisible(true);
    }//GEN-LAST:event_mTowerDHKMActionPerformed

    private void mTowerSpopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTowerSpopActionPerformed
        // TODO add your handling code here:
        FrmEditSpop editSpop = new FrmEditSpop(this, true,true,"Tower");
        editSpop.setVisible(true);
    }//GEN-LAST:event_mTowerSpopActionPerformed

    private void mToweLspopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mToweLspopActionPerformed
        // TODO add your handling code here:
        FrmEditLspopTower frmTower = new FrmEditLspopTower(this, true);
        frmTower.setVisible(true);
    }//GEN-LAST:event_mToweLspopActionPerformed

    private void mTowerPenilaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTowerPenilaianActionPerformed
        // TODO add your handling code here:
        FrmPenilaianTower frm = new FrmPenilaianTower(this,true);
        frm.setVisible(true);
    }//GEN-LAST:event_mTowerPenilaianActionPerformed

    private void lkokTanahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lkokTanahActionPerformed
        // TODO add your handling code here:
        FrmEditSpop editSpop = new FrmEditSpop(this, true,true,"Bandara");
        editSpop.setVisible(true);
    }//GEN-LAST:event_lkokTanahActionPerformed

    private void lkokBngUmumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lkokBngUmumActionPerformed
        // TODO add your handling code here:
        FrmLkokBangunanBandara lkokBng = new FrmLkokBangunanBandara(this,true);
        lkokBng.setVisible(true);
    }//GEN-LAST:event_lkokBngUmumActionPerformed

    private void lspopKhususActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lspopKhususActionPerformed
        // TODO add your handling code here:
        FrmEditLspopNonStd lspopNonStd = new FrmEditLspopNonStd(this,true,"Bandara");
        lspopNonStd.setVisible(true);
    }//GEN-LAST:event_lspopKhususActionPerformed

    private void prosesPenilaianBandaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesPenilaianBandaraActionPerformed
        // TODO add your handling code here:
        FrmPenilaianBandara penilBandara = new FrmPenilaianBandara(this,true);
        penilBandara.setVisible(true);
    }//GEN-LAST:event_prosesPenilaianBandaraActionPerformed

    private void lspopBandaraNonDbkbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lspopBandaraNonDbkbActionPerformed
        // TODO add your handling code here:
        FrmLspopBandara lspopBandara = new FrmLspopBandara(this,true);
        lspopBandara.setVisible(true);
    }//GEN-LAST:event_lspopBandaraNonDbkbActionPerformed

    private void spopPelabuhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spopPelabuhanActionPerformed
        // TODO add your handling code here:
        FrmEditSpop spopPelabuhan =  new FrmEditSpop(this,true,true,"Pelabuhan");
        spopPelabuhan.setVisible(true);
    }//GEN-LAST:event_spopPelabuhanActionPerformed

    private void hitungCrnPelabuhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungCrnPelabuhanActionPerformed
        // TODO add your handling code here:
        FrmPenilaianPelabuhan crnPelabuhan = new FrmPenilaianPelabuhan(this,true);
        crnPelabuhan.setVisible(true);
    }//GEN-LAST:event_hitungCrnPelabuhanActionPerformed

    private void kelolaPejabatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelolaPejabatActionPerformed
        // TODO add your handling code here:
        FrmEditReport editPejabat = new FrmEditReport(this,true);
        editPejabat.setVisible(true);
    }//GEN-LAST:event_kelolaPejabatActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem hitungCrnPelabuhan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem kelolaPejabat;
    private javax.swing.JLabel lbDispUser;
    private javax.swing.JMenuItem lkokBngUmum;
    private javax.swing.JMenuItem lkokTanah;
    private javax.swing.JMenuItem lspopBandaraNonDbkb;
    private javax.swing.JMenuItem lspopKhusus;
    private javax.swing.JMenu mDbkb;
    private javax.swing.JMenuItem mDhkf;
    private javax.swing.JMenuItem mDhkm;
    private javax.swing.JMenu mEditData;
    private javax.swing.JMenu mEditRef;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenuItem mHitDbkb;
    private javax.swing.JMenu mHubSismiop;
    private javax.swing.JMenuItem mImpSismiop;
    private javax.swing.JMenuItem mKeluar;
    private javax.swing.JMenuItem mKomFas;
    private javax.swing.JMenuItem mKompMat;
    private javax.swing.JMenuItem mKompUt;
    private javax.swing.JMenu mLihatDbkb;
    private javax.swing.JMenuItem mLihatHasilPenilaian;
    private javax.swing.JMenuItem mLspop;
    private javax.swing.JMenu mPenilKhusus;
    private javax.swing.JMenu mPenilUmum;
    private javax.swing.JMenuItem mProsesPenilaian;
    private javax.swing.JMenuItem mSalinDbkb;
    private javax.swing.JMenuItem mSpop;
    private javax.swing.JMenuItem mTambahPengguna;
    private javax.swing.JMenuItem mToweLspop;
    private javax.swing.JMenu mTower;
    private javax.swing.JMenuItem mTowerDHKM;
    private javax.swing.JMenu mTowerInputData;
    private javax.swing.JMenuItem mTowerPenilaian;
    private javax.swing.JMenuItem mTowerSpop;
    private javax.swing.JMenuItem mUbahProfil;
    private javax.swing.JMenuItem prosesPenilaianBandara;
    private javax.swing.JMenuItem spopPelabuhan;
    // End of variables declaration//GEN-END:variables

    private Pengguna pengguna = new Pengguna();
}
